In [35]:
import pandas as pd
from pycaret.classification import *
import numpy as np
from sklearn.metrics import confusion_matrix

# LOAD_DATA AND COMPAREMODELS(R,G)

In [244]:
pd.set_option('display.max_columns',None)

In [75]:
clean_data = pd.read_csv('../data/data_dropout_59-64(final_model).csv')

In [78]:
test = clean_data.sample(n = int(849*0.3),random_state=10)

In [79]:
test.to_csv('../data/data_dropout_59-64(final_model_test).csv',index=False)

In [80]:
train = clean_data.drop(test.index)

In [81]:
train.to_csv('../data/data_dropout_59-64(final_model_train).csv',index=False)

In [83]:
s = setup(train,target='STUDY_STATUS')

In [84]:
models = compare_models()

In [85]:
models

ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=3711, verbose=0, warm_start=False)

In [86]:
predictions = predict_model(models,data=test)

In [87]:
con = confusion_matrix(y_true=predictions['STUDY_STATUS'],y_pred=predictions['prediction_label'],labels=['R','G'])

In [88]:
con

array([[ 51,   8],
       [  5, 190]])

In [89]:
save_model(models,'model_top_no_STILL_STUDENT_2Class')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=FastMemory(location=/tmp/joblib),
          steps=[('clean_column_names',
                  TransformerWrapper(exclude=None, include=None,
                                     transformer=CleanColumnNames(match='[\\]\\[\\,\\{\\}\\"\\:]+'))),
                 ('label_encoding',
                  TransformerWrapperWithInverse(exclude=None, include=None,
                                                transformer=LabelEncoder())),
                 ('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     includ...
                  ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0,
                                       class_weight=None, criterion='gini',
                                       max_depth=None, max_features='sqrt',
                                       max_leaf_nodes=None, max_samples=None,
                                       min_impurity_decrease=0.0,
                                       min_samples_leaf=1, min_samples_split=2,
                                       min_weight_fraction_leaf=0.0,
                                       n_estimators=100, n_jobs=-1,
                                       oob_score=False, random_state=3711,
                                       verbose=0, warm_start=False))],
          verbose=False),
 'model_top_no_STILL_STUDENT_2Class.pkl')

In [90]:
models.feature_names_in_

array(['ADMIT_YEAR', 'MAJOR_ID', 'DEPT_ID', 'DEGREE_ID',
       'STUD_BIRTH_PROVINCE_ID', 'INSTITUTION_PROVINCE_ID', 'ENG_SCORE',
       'CAMPUS_ID', 'IS_GRAD_IN_COURSE', 'เกรดปี1เทอม1', 'เกรดปี1เทอม2',
       'เกรดปี2เทอม1', 'เกรดปี2เทอม2', 'เกรดปี3เทอม1', 'เกรดปี3เทอม2',
       'เกรดปี4เทอม1', 'เกรดปี4เทอม2', 'GPA_SCHOOL'], dtype=object)

# LOAD_DATA AND COMPAREMODELS(R,G,map_E_to_R)

In [148]:
clean_data = pd.read_csv('../data/data_dropout_59-64(4).csv')

In [149]:
clean_data = clean_data.drop(['STUDENT_ID','STATUS_DESC_THAI','STILL_STUDENT','ENT_METHOD','ENT_METHOD_DESC','PROVINCE_NAME_THAI','PREV_INSTITUTION_NAME','INSTITUTION_PROVINCE_NAME','PARENTS_MARRIED_NAME','PARENTS_MARRIED_NAME_CODE'],axis=1)

In [150]:
clean_data = clean_data[( (clean_data['STUDY_STATUS'] == 'G') & (clean_data['เกรดปี4เทอม1'] != 0) & (clean_data['เกรดปี3เทอม2'] != 0) ) | (clean_data['STUDY_STATUS'] == 'R') | (clean_data['STUDY_STATUS'] == 'E') ]

In [151]:
clean_data = clean_data[clean_data['INSTITUTION_PROVINCE_ID'] != 'XX']

In [152]:
clean_data = clean_data[clean_data['STUDY_STATUS'] != 'OK']

In [153]:
clean_data

,ADMIT_YEAR,MAJOR_ID,DEPT_ID,DEGREE_ID,STUDY_STATUS,STUD_BIRTH_PROVINCE_ID,INSTITUTION_PROVINCE_ID,ENG_SCORE,CAMPUS_ID,IS_GRAD_IN_COURSE,เกรดปี1เทอม1,เกรดปี1เทอม2,เกรดปี2เทอม1,เกรดปี2เทอม2,เกรดปี3เทอม1,เกรดปี3เทอม2,เกรดปี4เทอม1,เกรดปี4เทอม2,GPA_SCHOOL
1,2559,225,31,228.0,E,61,52,52.00,1,N,2.97,2.30,2.97,3.36,3.60,3.90,3.83,4.0,3.32
3,2559,215,30,218.0,R,60,56,21.00,1,Y,2.50,2.94,3.47,3.27,3.47,0.00,3.73,0.0,3.77
5,2559,215,30,218.0,G,64,64,20.00,1,Y,2.39,2.80,2.17,2.42,2.68,3.00,4.00,0.0,3.62
6,2559,220,29,223.0,G,60,54,39.00,1,Y,2.00,2.88,2.75,3.00,3.13,2.93,3.50,0.0,3.05
7,2559,215,30,218.0,G,62,62,37.00,1,Y,2.62,2.15,2.02,2.02,3.07,2.50,3.15,3.8,3.79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3481,2564,226,31,239.0,E,62,62,57.50,1,N,4.00,3.82,0.00,0.00,0.00,0.00,0.00,0.0,3.45
3483,2564,216,30,242.0,E,62,54,46.25,1,N,3.26,3.78,0.00,0.00,0.00,0.00,0.00,0.0,2.85
3484,2564,216,30,242.0,E,54,54,26.25,1,N,3.00,2.97,0.00,0.00,0.00,0.00,0.00,0.0,3.09
3492,2564,200,193,200.0,R,57,57,28.75,1,N,2.40,3.60,0.00,0.00,0.00,0.00,0.00,0.0,3.87
3494,2564,226,31,239.0,E,60,56,33.75,1,N,3.34,3.36,0.00,0.00,0.00,0.00,0.00,0.0,3.70

In [155]:
clean_data.to_csv('../data/data_dropout_59-64(clean_GER).csv',index=False)

In [156]:
clean_data = pd.read_csv('../data/data_dropout_59-64(clean_GER).csv')

In [157]:
clean_data['STUDY_STATUS'] = clean_data['STUDY_STATUS'].replace('E','R')

In [158]:
clean_data['STUDY_STATUS'].unique()

array(['R', 'G'], dtype=object)

In [279]:
clean_data.to_csv('../data/data_dropout_59-64(final_model_GR_map_E_to_R).csv',index=False)

In [159]:
test = clean_data.sample(n = int(849*0.3),random_state=10)

In [280]:
test.to_csv('../data/data_dropout_59-64(final_model_GR_map_E_to_R_test).csv',index=False)

In [281]:
train = clean_data.drop(test.index)

In [282]:
train.to_csv('../data/data_dropout_59-64(final_model_train).csv',index=False)

In [161]:
s = setup(train,target='STUDY_STATUS')

In [162]:
models = compare_models()

In [166]:
models

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=5359, splitter='best')

In [165]:
models.feature_names_in_

array(['ADMIT_YEAR', 'MAJOR_ID', 'DEPT_ID', 'DEGREE_ID',
       'STUD_BIRTH_PROVINCE_ID', 'INSTITUTION_PROVINCE_ID', 'ENG_SCORE',
       'CAMPUS_ID', 'IS_GRAD_IN_COURSE', 'เกรดปี1เทอม1', 'เกรดปี1เทอม2',
       'เกรดปี2เทอม1', 'เกรดปี2เทอม2', 'เกรดปี3เทอม1', 'เกรดปี3เทอม2',
       'เกรดปี4เทอม1', 'เกรดปี4เทอม2', 'GPA_SCHOOL'], dtype=object)

In [227]:
test = test.sort_index()

In [246]:
predictions = predict_model(models,data=test)

In [247]:
con = confusion_matrix(y_true=predictions['STUDY_STATUS'],y_pred=predictions['prediction_label'],labels=['R','G'])

In [248]:
con

array([[103,   7],
       [  8, 136]])

In [284]:
save_model(models,'model_top_no_STILL_STUDENT_2Class_map_E_to_R')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=FastMemory(location=/tmp/joblib),
          steps=[('clean_column_names',
                  TransformerWrapper(exclude=None, include=None,
                                     transformer=CleanColumnNames(match='[\\]\\[\\,\\{\\}\\"\\:]+'))),
                 ('label_encoding',
                  TransformerWrapperWithInverse(exclude=None, include=None,
                                                transformer=LabelEncoder())),
                 ('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     includ...
                                                                          'data_type': dtype('O'),
                                                                          'mapping': N      0
 Y      1
 NaN   -1
 dtype: int64}],
                                                                return_df=True,
                                                                verbose=0))),
                 ('trained_model',
                  DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None,
                                         criterion='gini', max_depth=None,
                                         max_features=None, max_leaf_nodes=None,
                                         min_impurity_decrease=0.0,
                                         min_samples_leaf=1, min_samples_split=2,
                                         min_weight_fraction_leaf=0.0,
                                         random_state=5359, splitter='best'))],
          verbose=False),
 'model_top_no_STILL_STUDENT_2Class_map_E_to_R.pkl')

In [285]:
models.feature_names_in_

array(['ADMIT_YEAR', 'MAJOR_ID', 'DEPT_ID', 'DEGREE_ID',
       'STUD_BIRTH_PROVINCE_ID', 'INSTITUTION_PROVINCE_ID', 'ENG_SCORE',
       'CAMPUS_ID', 'IS_GRAD_IN_COURSE', 'เกรดปี1เทอม1', 'เกรดปี1เทอม2',
       'เกรดปี2เทอม1', 'เกรดปี2เทอม2', 'เกรดปี3เทอม1', 'เกรดปี3เทอม2',
       'เกรดปี4เทอม1', 'เกรดปี4เทอม2', 'GPA_SCHOOL'], dtype=object)

In [231]:
compare = pd.read_csv('../data/data_dropout_59-64(clean_GER).csv')

In [232]:
compare_test = compare.drop(train.index)

In [235]:
compare_test = compare_test.set_index(np.arange(254))

In [272]:
compare_test_ = pd.DataFrame([predictions['prediction_label'],predictions['STUDY_STATUS'],compare_test['STUDY_STATUS']],index=['prediction_label','STUDY_STATUS_map','STUDY_STATUS']).T

In [278]:
compare_test_[compare_test_['STUDY_STATUS'] == 'R']

    prediction_label STUDY_STATUS_map STUDY_STATUS
0                  G                R            R
3                  R                R            R
7                  R                R            R
14                 R                R            R
48                 R                R            R
51                 R                R            R
58                 R                R            R
62                 R                R            R
67                 R                R            R
70                 R                R            R
71                 R                R            R
83                 R                R            R
84                 R                R            R
91                 R                R            R
96                 R                R            R
97                 R                R            R
139                R                R            R
149                R                R            R
151                R                R            R
152                R                R            R
155                R                R            R
161                G                R            R
166                R                R            R
167                G                R            R
168                R                R            R
170                R                R            R
182                R                R            R
209                R                R            R
214                R                R            R
217                R                R            R
219                R                R            R
223                R                R            R
225                R                R            R
234                R                R            R
235                R                R            R
237                R                R            R
239                R                R            R
242                R                R            R
246                R                R            R
250                R                R            R
251                R                R            R
252                R                R            R

# LOAD_MODEL DATA AND PREDICT

In [91]:
model_ = load_model('model_top_no_STILL_STUDENT_2Class')

Transformation Pipeline and Model Successfully Loaded

In [56]:
data_test = pd.read_csv('../data/data_dropout_59-64(4).csv')

In [60]:
dataa = data_test.drop(['STUDENT_ID','STUDY_STATUS','STATUS_DESC_THAI','STILL_STUDENT','ENT_METHOD','ENT_METHOD_DESC','PROVINCE_NAME_THAI','PREV_INSTITUTION_NAME','INSTITUTION_PROVINCE_NAME','PARENTS_MARRIED_NAME','PARENTS_MARRIED_NAME_CODE'],axis=1)

In [117]:
dataa

,ADMIT_YEAR,MAJOR_ID,DEPT_ID,DEGREE_ID,STUD_BIRTH_PROVINCE_ID,INSTITUTION_PROVINCE_ID,ENG_SCORE,CAMPUS_ID,IS_GRAD_IN_COURSE,เกรดปี1เทอม1,เกรดปี1เทอม2,เกรดปี2เทอม1,เกรดปี2เทอม2,เกรดปี3เทอม1,เกรดปี3เทอม2,เกรดปี4เทอม1,เกรดปี4เทอม2,GPA_SCHOOL
0,2559,215,30,218.0,53,62,41.00,1,Y,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,3.10
1,2559,225,31,228.0,61,52,52.00,1,N,2.97,2.30,2.97,3.36,3.60,3.9,3.83,4.00,3.32
2,2559,210,28,213.0,62,62,28.00,1,Y,1.73,1.05,0.00,0.00,0.00,0.0,0.00,0.00,3.78
3,2559,215,30,218.0,60,56,21.00,1,Y,2.50,2.94,3.47,3.27,3.47,0.0,3.73,0.00,3.77
4,2559,235,33,240.0,63,63,21.00,1,Y,1.93,2.08,1.78,0.00,1.41,0.0,1.22,0.72,3.21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3505,2564,210,28,213.0,60,60,22.50,1,N,2.70,2.48,0.00,0.00,0.00,0.0,0.00,0.00,3.54
3506,2564,226,31,239.0,63,63,37.50,1,N,3.27,3.27,0.00,0.00,0.00,0.0,0.00,0.00,3.74
3507,2564,203,193,254.0,62,62,61.25,1,N,2.56,3.15,0.00,0.00,0.00,0.0,0.00,0.00,3.25
3508,2564,203,193,254.0,63,63,21.25,1,N,3.64,3.50,0.00,0.00,0.00,0.0,0.00,0.00,2.79
3509,2564,203,193,254.0,54,58,56.25,1,N,3.17,2.78,0.00,0.00,0.00,0.0,0.00,0.00,3.26

In [103]:
dataa = dataa[dataa['INSTITUTION_PROVINCE_ID'] != 'XX']

In [106]:
data_test = data_test[data_test['INSTITUTION_PROVINCE_ID'] != 'XX']

In [104]:
predictions = predict_model(model_,data=dataa)

In [107]:
predictions['STUDY_STATUS'] = data_test['STUDY_STATUS']

In [116]:
for i in predictions[predictions['STUDY_STATUS'] == 'E']['prediction_label']:
    print(i)

G
G
G
R
R
R
G
R
R
R
G
R
G
R
R
R
R
G
R
R
R
R
R
R
R
R
R
R
G
R
R
R
R
G
R
R
R
R
R
R
R
G
G
R
R
R
R
R
R
R
G
R
R
R
G
G
R
G
R
G
G
G
G
R
R
R
R
R
R
R
G
R
R
R
R
R
R
G
R
R
G
R
G
R
R
G
R
R
R
R
R
R
R
R
R
G
R
R
R
R
R
R
G
R
R
G
R
R
R
R
R
R
R
R
G
R
R
R
R
R
R
G
R
G
G
G
R
G
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
G
R
G
R
G
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R
R

In [ ]:
confusion = confusion_matrix(y_true=predictions['STUDY_STATUS'],y_pred=predictions['prediction_label'],labels=['R','G'])

In [44]:
confusion

array([[206,   8],
       [ 11, 624]])

In [63]:
model_.feature_names_in_

['STUDENT_ID',
 'ADMIT_YEAR',
 'MAJOR_ID',
 'DEPT_ID',
 'DEGREE_ID',
 'STUD_BIRTH_PROVINCE_ID',
 'INSTITUTION_PROVINCE_ID',
 'ENG_SCORE',
 'CAMPUS_ID',
 'IS_GRAD_IN_COURSE',
 'เกรดปี1เทอม1',
 'เกรดปี1เทอม2',
 'เกรดปี2เทอม1',
 'เกรดปี2เทอม2',
 'เกรดปี3เทอม1',
 'เกรดปี3เทอม2',
 'เกรดปี4เทอม1',
 'เกรดปี4เทอม2',
 'GPA_SCHOOL',
 'STUDY_STATUS']