In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import json

In [2]:
raw_datas = pd.read_excel("../data/data_dropout_59-64.xlsx")

In [3]:
pd.set_option('display.max_columns',None)

In [4]:
raw_datas.columns.to_list().index('เกรดปี1เทอม1')

41

In [5]:
raw_datas

,STUDENT_ID,ADMIT_YEAR,ADMIT_TERM,MAJOR_ID,MAJOR_NAME_THAI,DEPT_ID,DEPT_NAME_THAI,FAC_ID,FAC_NAME_THAI,STUDY_LEVEL_ID,STUDY_LEVEL_NAME,STUDY_TYPE_ID,STUDY_TYPE_NAME,STUDY_PLAN_NAME,DEGREE_ID,COURSE_NAME,COURSE_DEGREE,COURSE_TYPE_NAME,STUDY_STATUS,STATUS_DESC_THAI,STILL_STUDENT,NATIONALITY,SEX_SHORT_NAME_THAI,SEX_NAME_THAI,ENT_METHOD,ENT_METHOD_DESC,STUD_BIRTH_DATE,STUD_BIRTH_PROVINCE_ID,PROVINCE_NAME_THAI,BIRTH_COUNTRY,COUNTRY_NAME_ENG,PREV_INSTITUTION_NAME,INSTITUTION_PROVINCE_ID,INSTITUTION_PROVINCE_NAME,ENG_SCORE,CAMPUS_ID,CAMPUS_NAME_THAI,IS_GRAD_IN_COURSE,CURR_REG,IN_PROVINCE,IN_PROVINCE_CAMPUS,เกรดปี1เทอม1,เกรดปี1เทอม2,เกรดปี1เทอม3,เกรดปี2เทอม1,เกรดปี2เทอม2,เกรดปี2เทอม3,เกรดปี3เทอม1,เกรดปี3เทอม2,เกรดปี3เทอม3,เกรดปี4เทอม1,เกรดปี4เทอม2,เกรดปี4เทอม3,GPA_SCHOOL,FUND_NAME,FUND_NAME_CODE,DEFORMITY_NAME,DEFORMITY_NAME_code,PARENTS_MARRIED_NAME,PARENTS_MARRIED_NAME_CODE
0,Y6rAL6a3ug,2559.0,1.0,215.0,วิศวกรรมเครื่องกล,30.0,ภาควิชาวิศวกรรมเครื่องกล,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,218.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมเครื่องกล),หลักสูตรปกติ,G,สำเร็จการศึกษา (พ้นสภาพการเป็นนักศึกษา),N,T,ช,ชาย,77,โครงการคัดเลือกบุคคลเข้าศึกษาโดยใช้ผลคะแนนสอบ ...,1997-11-16,53.0,ตรัง,TH,THAILAND,โรงเรียนหาดใหญ่วิทยาลัยสมบูรณ์กุลกันยา,62,สงขลา,41.00,1.0,วิทยาเขตหาดใหญ่,Y,FT,N,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.10,ไม่ได้รับทุน,N,ไม่พิการ,N,อยู่ด้วยกัน,9.0
1,ihEYqG7Q2P,2559.0,1.0,225.0,วิศวกรรมอุตสาหการ,31.0,ภาควิชาวิศวกรรมอุตสาหการ,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,228.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมอุตสาหการ),หลักสูตรปกติ,E,ลาออก (พ้นสภาพการเป็นนักศึกษา),N,T,ญ,หญิง,01,โครงการคัดเลือกนักเรียนใน 14 จังหวัดภาคใต้ เข...,1998-01-12,61.0,ระนอง,TH,THAILAND,โรงเรียนศรียาภัย,52,ชุมพร,52.00,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,2.97,2.30,2.50,2.97,3.36,2.75,3.60,3.9,0.00,3.83,4.00,NaN,3.32,ไม่ได้รับทุน,N,ไม่พิการ,N,อยู่ด้วยกัน,9.0
2,EJwFAHDeDB,2559.0,1.0,210.0,วิศวกรรมไฟฟ้า,28.0,ภาควิชาวิศวกรรมไฟฟ้า,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,213.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมไฟฟ้า),หลักสูตรปกติ,G,สำเร็จการศึกษา (พ้นสภาพการเป็นนักศึกษา),N,T,ญ,หญิง,40,"โครงการ ""ทุนมงคลสุข""",1997-02-24,62.0,สงขลา,TH,THAILAND,โรงเรียนจะนะชนูปถัมภ์,62,สงขลา,28.00,1.0,วิทยาเขตหาดใหญ่,Y,FT,Y,Y,1.73,1.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.78,ได้รับทุน,Y,ไม่พิการ,N,บิดาและมารดาแต่งงานใหม่,4.0
3,mAN7tIZz44,2559.0,1.0,215.0,วิศวกรรมเครื่องกล,30.0,ภาควิชาวิศวกรรมเครื่องกล,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,218.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมเครื่องกล),หลักสูตรปกติ,R,ตกออก (พ้นสภาพการเป็นนักศึกษา),N,T,ช,ชาย,01,โครงการคัดเลือกนักเรียนใน 14 จังหวัดภาคใต้ เข...,1997-09-01,60.0,ยะลา,TH,THAILAND,โรงเรียนราชมุนีรังสฤษฏ์,56,ปัตตานี,21.00,1.0,วิทยาเขตหาดใหญ่,Y,FT,N,N,2.50,2.94,3.25,3.47,3.27,3.23,3.47,0.0,3.31,3.73,NaN,NaN,3.77,ได้รับทุน,Y,ไม่พิการ,N,บิดาถึงแก่กรรม,6.0
4,rWseDSww8R,2559.0,1.0,235.0,วิศวกรรมเหมืองแร่,33.0,ภาควิชาวิศวกรรมเหมืองแร่และวัสดุ,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,240.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมเหมืองแร่),หลักสูตรปกติ,G,สำเร็จการศึกษา (พ้นสภาพการเป็นนักศึกษา),N,T,ช,ชาย,38,โครงการรับนักเรียนที่มีผลการเรียนดี,1997-10-05,63.0,สตูล,TH,THAILAND,โรงเรียนจุฬาภรณราชวิทยาลัย สตูล,63,สตูล,21.00,1.0,วิทยาเขตหาดใหญ่,Y,FT,N,N,1.93,2.08,1.86,1.78,0.00,2.08,1.41,0.0,0.87,1.22,0.72,0.0,3.21,ไม่ได้รับทุน,N,ไม่พิการ,N,อยู่ด้วยกัน,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4116,IY8jWx00mt,2564.0,1.0,226.0,วิศวกรรมการผลิต,31.0,ภาควิชาวิศวกรรมอุตสาหการ,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,239.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมการผลิต),หลักสูตรปกติ,OK,กำลังศึกษา,Y,T,ช,ชาย,39,"โครงการ ""โควตาวิศวกรรมศาสตร์ มอ.""",2002-08-25,63.0,สตูล,TH,THAILAND,โรงเรียนควนโดนวิทยา,63,สตูล,37.50,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,3.27,3.27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.74,NaN,other,ไม่พิการ,N,อยู่ด้วยกัน,9.0
4117,uVfxDYkac8,2564.0,1.0,203.0,วิศวกรรมและการจัดการนวัตกรรม,193.0,คณะวิศวกรรมศาสตร์,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,4.0,ภาคปกติ (นานาชาติ),แผนการศึกษา ป.ตรี,254.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมและการจัดการนวัตก...,หลักสูตรนานาชาติ,OK,กำลังศึกษา,Y,T,ญ,หญิง,P4,โครงการคัดเลือกนักเรียนเข้าศึกษาในคณะวิศวกรรมศ...,2003-02-25,62.0,สงขลา,TH,THAILAND,โรงเรียนธิดานุเคราะห์,62,สงขลา,61.25,1.0,วิทยาเขตหาดใหญ่,N,FT,Y,Y,2.56,3.15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.25,NaN,other,ไม่พิการ,N,อยู่ด้วยกัน,9.0
4118,IcXALKhfPP,2564.0,1.0,203.0,วิศวกรรมและการจัดการนวัตกรรม,193.0,คณะวิศวกรรมศาสตร์,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,4.0,ภาคปกติ (นานาชาติ),แผนการศึกษา ป.ตรี,254.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมและการจัดการนวัตก...,หลักสูตรนานาชาติ,OK,กำลังศึกษา,Y,T,ช,ชาย,P4,โครงการคัดเลือกนักเรียนเข้าศึกษาในคณะวิศวกรรมศ...,1998-04-01,63.0,สตูล,TH,THAILAND,โรงเรียนดารุลมาอาเรฟมูลนิธิ,63,สตูล,21.25,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,3.64,3.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.79,NaN,other,ไม่พิการ,N,มารดาถึงแก่กรรม,8.0
4119,q5SWpcypnh,2564.0,1.0,203.0,วิศวกรรมและการจัดการนวัตกรรม,193.0,คณะวิศวกรรมศาสตร์,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,4.0,ภาคปกติ (นานาชาติ),แผนการศึกษา ป.ตรี,254.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมและการจัดการนวัตก...,หลักสูตรนานาชาติ,OK,กำลังศึกษา,Y,T,ช,ชาย,P4,โครงการคัดเลือกนักเรียนเข้าศึกษาในคณะวิศวกรรมศ...,2003-01-30,54.0,นครศรีธรรมราช,TH,THAILAND,โรงเรียนปากพะยูนพิทยาคาร,58,พัทลุง,56.25,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,3.17,2.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.26,ไม่ได้รับทุน,N,ไม่พิการ,N,อยู่ด้วยกัน,9.0
4120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.50,3.18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
raw_datas.iloc[:,41:53].replace(np.nan,0)

,เกรดปี1เทอม1,เกรดปี1เทอม2,เกรดปี1เทอม3,เกรดปี2เทอม1,เกรดปี2เทอม2,เกรดปี2เทอม3,เกรดปี3เทอม1,เกรดปี3เทอม2,เกรดปี3เทอม3,เกรดปี4เทอม1,เกรดปี4เทอม2,เกรดปี4เทอม3
0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0
1,2.97,2.30,2.50,2.97,3.36,2.75,3.60,3.9,0.00,3.83,4.00,0.0
2,1.73,1.05,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0
3,2.50,2.94,3.25,3.47,3.27,3.23,3.47,0.0,3.31,3.73,0.00,0.0
4,1.93,2.08,1.86,1.78,0.00,2.08,1.41,0.0,0.87,1.22,0.72,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
4116,3.27,3.27,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0
4117,2.56,3.15,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0
4118,3.64,3.50,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0
4119,3.17,2.78,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0
4120,3.50,3.18,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0

In [7]:
raw_datas.iloc[:,41:53] = raw_datas.iloc[:,41:53].replace(np.nan,0)

In [8]:
raw_datas = raw_datas.drop([4120])

In [9]:
raw_datas.to_excel('../data/data_dropout_59-64(1).xlsx',index=False)

In [10]:
raw_datas.to_csv("../data/data_dropout_59-64(1).csv",index=False)

In [11]:
raw_datas = pd.read_csv('../data/data_dropout_59-64(1).csv')

In [12]:
raw_datas.describe()

,ADMIT_YEAR,ADMIT_TERM,MAJOR_ID,DEPT_ID,FAC_ID,STUDY_LEVEL_ID,STUDY_TYPE_ID,DEGREE_ID,STUD_BIRTH_PROVINCE_ID,ENG_SCORE,CAMPUS_ID,เกรดปี1เทอม1,เกรดปี1เทอม2,เกรดปี1เทอม3,เกรดปี2เทอม1,เกรดปี2เทอม2,เกรดปี2เทอม3,เกรดปี3เทอม1,เกรดปี3เทอม2,เกรดปี3เทอม3,เกรดปี4เทอม1,เกรดปี4เทอม2,เกรดปี4เทอม3,GPA_SCHOOL,PARENTS_MARRIED_NAME_CODE
count,4120.000000,4120.0,4120.000000,4120.000000,4120.0,4120.0,4120.000000,3929.000000,4120.000000,4120.000000,4120.000000,4120.000000,4120.000000,4120.000000,4120.000000,4120.000000,4120.000000,4120.000000,4120.000000,4120.000000,4120.000000,4120.000000,4120.000000,4120.000000,4120.000000
mean,2561.509709,1.0,223.618447,40.578398,6.0,6.0,1.021117,229.274370,55.478155,33.253233,1.101942,2.595354,2.347888,2.010711,1.884255,1.699410,1.633296,1.267546,1.077274,0.964517,0.783687,0.399456,0.180046,3.936075,8.417718
std,1.725634,0.0,13.463033,38.382452,0.0,0.0,0.283547,15.947711,12.987940,14.744414,0.439930,0.673865,0.821624,1.317043,1.249843,1.503292,1.507769,1.426436,1.461330,1.465526,1.353027,1.032799,0.673702,47.562423,1.969672
min,2559.000000,1.0,200.000000,28.000000,6.0,6.0,1.000000,149.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,2560.000000,1.0,215.000000,29.000000,6.0,6.0,1.000000,218.000000,54.000000,25.000000,1.000000,2.180000,1.920000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.960000,9.000000
50%,2562.000000,1.0,225.000000,31.000000,6.0,6.0,1.000000,233.000000,59.000000,32.000000,1.000000,2.640000,2.380000,2.350000,2.260000,2.020000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.220000,9.000000
75%,2563.000000,1.0,235.000000,33.000000,6.0,6.0,1.000000,242.000000,62.000000,41.250000,1.000000,3.070000,2.890000,3.000000,2.870000,3.000000,3.000000,2.660000,2.590000,2.410000,1.622500,0.000000,0.000000,3.450000,9.000000
max,2564.000000,1.0,254.000000,193.000000,6.0,6.0,7.000000,254.000000,78.000000,93.750000,3.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,3056.000000,11.000000

In [13]:
raw_datas = raw_datas[raw_datas['GPA_SCHOOL'] <= 4.00]

In [14]:
raw_datas['CAMPUS_NAME_THAI'].unique()

array(['วิทยาเขตหาดใหญ่', 'วิทยาเขตภูเก็ต'], dtype=object)

In [15]:
raw_datas['COURSE_DEGREE'].unique()

array(['วิศวกรรมศาสตรบัณฑิต (วิศวกรรมเครื่องกล)',
       'วิศวกรรมศาสตรบัณฑิต (วิศวกรรมอุตสาหการ)',
       'วิศวกรรมศาสตรบัณฑิต (วิศวกรรมไฟฟ้า)',
       'วิศวกรรมศาสตรบัณฑิต (วิศวกรรมเหมืองแร่)',
       'วิศวกรรมศาสตรบัณฑิต (วิศวกรรมโยธา)',
       'วิศวกรรมศาสตรบัณฑิต (วิศวกรรมเคมี)',
       'วิศวกรรมศาสตรบัณฑิต (วิศวกรรมเมคาทรอนิกส์)',
       'วิศวกรรมศาสตรบัณฑิต (วิศวกรรมวัสดุ)', 'รอระบุหลักสูตร',
       'วิศวกรรมศาสตรบัณฑิต (วิศวกรรมคอมพิวเตอร์)',
       'วิศวกรรมศาสตรบัณฑิต (วิศวกรรมการผลิต)',
       'วิศวกรรมศาสตรบัณฑิต (วิศวกรรมชีวการแพทย์)',
       'วิศวกรรมศาสตรบัณฑิต (วิศวกรรมสิ่งแวดล้อม)',
       'วิศวกรรมศาสตรบัณฑิต (วิศวกรรมและการจัดการนวัตกรรม)',
       'วิศวกรรมศาสตรบัณฑิต (วิศวกรรมเหมืองแร่และวัสดุ)',
       'วิศวกรรมศาสตรบัณฑิต (วิศวกรรมปัญญาประดิษฐ์)',
       'วิศวกรรมศาสตรบัณฑิต'], dtype=object)

In [16]:
for i in raw_datas[(raw_datas['COURSE_DEGREE'] == 'วิศวกรรมศาสตรบัณฑิต (วิศวกรรมคอมพิวเตอร์)') & (raw_datas['COURSE_NAME'] == 'วิศวกรรมศาสตรบัณฑิต')]['STUDY_STATUS']:
    print(i)

R
G
E
G
OK
R
G
E
G
G
G
G
R
E
E
OK
R
E
R
E
G
G
R
OK
R
OK
E
G
G
R
R
E
OK
G
G
G
G
G
E
G
G
E
G
G
E
G
G
OK
G
E
R
G
G
OK
G
G
OK
G
R
G
R
G
G
OK
G
G
G
R
R
G
G
R
G
R
R
G
OK
G
G
G
R
R
G
G
R
G
OK
E
G
E
R
G
G
R
G
R
G
G
OK
G
G
G
R
G
OK
G
G
R
E
G
G
G
R
G
OK
G
OK
OK
G
G
G
G
E
G
G
E
E
G
G
G
G
G
G
OK
G
G
G
G
G
G
G
G
R
G
G
R
E
E
R
OK
G
G
OK
G
R
OK
OK
OK
G
OK
G
OK
G
G
G
G
E
G
E
G
OK
OK
G
G
E
D
G
R
OK
G
OK
OK
OK
G
G
G
OK
G
G
G
OK
G
OK
OK
OK
E
OK
OK
E
R
R
OK
OK
G
G
R
OK
OK
G
OK
G
E
OK
G
OK
E
OK
G
E
OK
R
G
G
G
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
E
OK
OK
OK
OK
OK
OK
OK
OK
OK
R
OK
OK
OK
OK
R
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
D
R
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
E
R
OK
OK
R
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
R
OK
OK
OK
OK
OK
OK
R
OK
OK
E
OK
OK
OK
OK
OK
OK
OK
E
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
E
OK
OK
OK
OK
OK
R
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
R
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
R
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
E
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
R
OK
OK
OK
OK
OK
OK
OK
OK
OK
E
E
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
R
OK
OK
OK
OK
D
OK
OK
OK
OK
OK
R
OK
OK
OK
OK
E
E
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
E
OK
OK
OK
OK
OK
OK
OK
OK
OK
E
OK
OK
OK
OK

In [17]:
for i in raw_datas[(raw_datas['COURSE_DEGREE'] == 'วิศวกรรมศาสตรบัณฑิต (วิศวกรรมคอมพิวเตอร์)') & (raw_datas['COURSE_NAME'] == 'วิศวกรรมศาสตรบัณฑิต (วิศวกรรมคอมพิวเตอร์)')]['STUDY_STATUS']:
    print(i)

G
G
G
G
G
G
G
G
G
G
OK
OK
G
G
G
G
G
OK
R
G
E
G
E
G
G
G
G
G
G
E
G
G
G
G
G
OK
G
G
OK
R
G
E
E
G
E
E
G
G
OK
OK
OK
G
OK
G
G
OK
E
G
G
R
G
OK
G
G
R
G
G
G
G
G
E
R
G
OK
G
E
R
OK
OK
G
G
G
OK
OK
G
OK
G
G
G
G
G
G
G
G
G
G
G
G
G
OK
E
OK
G
OK
E
D
G
OK
OK
OK
R
G
OK
D
E
G
OK
G
R
D
G
G
G
OK
G
E
OK
G
G
G
OK
G
OK
E
R
G
OK
OK
G
G
R
G
OK
OK
G
OK
OK
OK
G
R
G
G
G
G
G
E
OK
R
OK
G
R
E
G
G
G
G
G
OK
OK
OK
OK
G
G
OK
OK
OK
OK
OK
OK
OK
G
G
OK
OK
R
G
G
OK
G
OK
G
G
E
E
OK
G
OK
OK
G
E
E
OK
OK
OK
G
G
OK
G
OK
G

In [18]:
raw_datas[raw_datas['SEX_SHORT_NAME_THAI'] == 'ช']['STUDY_STATUS']

0        G
3        R
4        G
5        G
6        G
        ..
4114    OK
4115    OK
4116    OK
4118    OK
4119    OK
Name: STUDY_STATUS, Length: 2627, dtype: object

In [19]:
for i in raw_datas[raw_datas['CAMPUS_NAME_THAI'] == 'วิทยาเขตภูเก็ต']['DEGREE_ID']:
    print(i)

243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0
243.0

In [20]:
for i in raw_datas[raw_datas['STUDY_PLAN_NAME'] != 'แผนการศึกษา ป.ตรี']['STUDY_STATUS']:
    print(i)

R
R
E
E
E
R
E
R
E
E
E
R
R
R
E
R
E
R
E
R
E
R
R
E
E
E
R
R
R
R
E
R
R
R
E
R
E
R
R
R
R
I
R
R
E
R
R
R
R
E
E
E
E
R
E
E
R
R
E
E
R
E
E
E
R
E
E
E
E
E
R
E
E
E
E
R
R
E
E
E
E
R
E
E
R
E
E
E
R
R
R
R
E
E
E
E
E
R
R
R
R
R
E
E
R
E
R
R
E
E
E
E
E
E
E
R
E
E
E
R
R
E
E
E
E
E
R
E
E
E
R
E
R
R
E
E
R
E
E
E
E
R
R
E
E
R
E
E
E
E
R
R
E
E
R
R
R
E
R
R
E
E
E
E
R
E
E
E
R
E
R
R
E
E
R
R
E
E
E
E
E
R
E
R
R
E
R
R
R
E
E

In [21]:
major = dict()

In [22]:
dept = dict()

In [23]:
degree = dict()

In [24]:
campus = dict()

In [25]:
map_data = dict()

In [26]:
raw_datas['DEGREE_ID'] = raw_datas['DEGREE_ID'].replace(np.nan,0)

In [27]:
for i,n in zip(raw_datas['CAMPUS_ID'].unique(),raw_datas['CAMPUS_NAME_THAI'].unique()):
    campus[str(int(i))] = n

In [28]:
campus

{'1': 'วิทยาเขตหาดใหญ่', '3': 'วิทยาเขตภูเก็ต'}

In [29]:
map_data['degree'] = degree

In [30]:
map_data

{'degree': {}}

In [31]:
degree = {'218': 'วิศวกรรมศาสตรบัณฑิต (วิศวกรรมเครื่องกล)',
 '228': 'วิศวกรรมศาสตรบัณฑิต (วิศวกรรมอุตสาหการ)',
 '213': 'วิศวกรรมศาสตรบัณฑิต (วิศวกรรมไฟฟ้า)',
 '240': 'วิศวกรรมศาสตรบัณฑิต (วิศวกรรมเหมืองแร่)',
 '223': 'วิศวกรรมศาสตรบัณฑิต (วิศวกรรมโยธา)',
 '233': 'วิศวกรรมศาสตรบัณฑิต (วิศวกรรมเคมี)',
 '242': 'วิศวกรรมศาสตรบัณฑิต (วิศวกรรมเมคาทรอนิกส์)',
 '238': 'วิศวกรรมศาสตรบัณฑิต (วิศวกรรมวัสดุ)',
 '0': 'รอระบุหลักสูตร',
 '243': 'วิศวกรรมศาสตรบัณฑิต (วิศวกรรมคอมพิวเตอร์)',
 '239': 'วิศวกรรมศาสตรบัณฑิต (วิศวกรรมการผลิต)',
 '211': 'วิศวกรรมศาสตรบัณฑิต (วิศวกรรมชีวการแพทย์)',
 '245': 'วิศวกรรมศาสตรบัณฑิต (วิศวกรรมสิ่งแวดล้อม)',
 '254': 'วิศวกรรมศาสตรบัณฑิต (วิศวกรรมและการจัดการนวัตกรรม)',
 '149': 'วิศวกรรมศาสตรบัณฑิต (วิศวกรรมเหมืองแร่และวัสดุ)',
 '252': 'วิศวกรรมศาสตรบัณฑิต (วิศวกรรมปัญญาประดิษฐ์)',
 '200': 'วิศวกรรมศาสตรบัณฑิต'}

In [32]:
type(degree)

dict

In [33]:
with open('../data/map_datas.json','w') as f:
    json.dump(map_data,f)

In [34]:
with open('../data/map_datas.json','r') as f:
    map_data = json.load(f)

In [35]:
map_data['degree']

{}

In [36]:
raw_datas = raw_datas.drop(columns=['CAMPUS_NAME_THAI'])

In [37]:
raw_datas

,STUDENT_ID,ADMIT_YEAR,ADMIT_TERM,MAJOR_ID,MAJOR_NAME_THAI,DEPT_ID,DEPT_NAME_THAI,FAC_ID,FAC_NAME_THAI,STUDY_LEVEL_ID,STUDY_LEVEL_NAME,STUDY_TYPE_ID,STUDY_TYPE_NAME,STUDY_PLAN_NAME,DEGREE_ID,COURSE_NAME,COURSE_DEGREE,COURSE_TYPE_NAME,STUDY_STATUS,STATUS_DESC_THAI,STILL_STUDENT,NATIONALITY,SEX_SHORT_NAME_THAI,SEX_NAME_THAI,ENT_METHOD,ENT_METHOD_DESC,STUD_BIRTH_DATE,STUD_BIRTH_PROVINCE_ID,PROVINCE_NAME_THAI,BIRTH_COUNTRY,COUNTRY_NAME_ENG,PREV_INSTITUTION_NAME,INSTITUTION_PROVINCE_ID,INSTITUTION_PROVINCE_NAME,ENG_SCORE,CAMPUS_ID,IS_GRAD_IN_COURSE,CURR_REG,IN_PROVINCE,IN_PROVINCE_CAMPUS,เกรดปี1เทอม1,เกรดปี1เทอม2,เกรดปี1เทอม3,เกรดปี2เทอม1,เกรดปี2เทอม2,เกรดปี2เทอม3,เกรดปี3เทอม1,เกรดปี3เทอม2,เกรดปี3เทอม3,เกรดปี4เทอม1,เกรดปี4เทอม2,เกรดปี4เทอม3,GPA_SCHOOL,FUND_NAME,FUND_NAME_CODE,DEFORMITY_NAME,DEFORMITY_NAME_code,PARENTS_MARRIED_NAME,PARENTS_MARRIED_NAME_CODE
0,Y6rAL6a3ug,2559.0,1.0,215.0,วิศวกรรมเครื่องกล,30.0,ภาควิชาวิศวกรรมเครื่องกล,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,218.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมเครื่องกล),หลักสูตรปกติ,G,สำเร็จการศึกษา (พ้นสภาพการเป็นนักศึกษา),N,T,ช,ชาย,77,โครงการคัดเลือกบุคคลเข้าศึกษาโดยใช้ผลคะแนนสอบ ...,1997-11-16,53.0,ตรัง,TH,THAILAND,โรงเรียนหาดใหญ่วิทยาลัยสมบูรณ์กุลกันยา,62,สงขลา,41.00,1.0,Y,FT,N,Y,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,3.10,ไม่ได้รับทุน,N,ไม่พิการ,N,อยู่ด้วยกัน,9.0
1,ihEYqG7Q2P,2559.0,1.0,225.0,วิศวกรรมอุตสาหการ,31.0,ภาควิชาวิศวกรรมอุตสาหการ,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,228.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมอุตสาหการ),หลักสูตรปกติ,E,ลาออก (พ้นสภาพการเป็นนักศึกษา),N,T,ญ,หญิง,01,โครงการคัดเลือกนักเรียนใน 14 จังหวัดภาคใต้ เข...,1998-01-12,61.0,ระนอง,TH,THAILAND,โรงเรียนศรียาภัย,52,ชุมพร,52.00,1.0,N,FT,N,N,2.97,2.30,2.50,2.97,3.36,2.75,3.60,3.9,0.00,3.83,4.00,0.0,3.32,ไม่ได้รับทุน,N,ไม่พิการ,N,อยู่ด้วยกัน,9.0
2,EJwFAHDeDB,2559.0,1.0,210.0,วิศวกรรมไฟฟ้า,28.0,ภาควิชาวิศวกรรมไฟฟ้า,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,213.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมไฟฟ้า),หลักสูตรปกติ,G,สำเร็จการศึกษา (พ้นสภาพการเป็นนักศึกษา),N,T,ญ,หญิง,40,"โครงการ ""ทุนมงคลสุข""",1997-02-24,62.0,สงขลา,TH,THAILAND,โรงเรียนจะนะชนูปถัมภ์,62,สงขลา,28.00,1.0,Y,FT,Y,Y,1.73,1.05,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,3.78,ได้รับทุน,Y,ไม่พิการ,N,บิดาและมารดาแต่งงานใหม่,4.0
3,mAN7tIZz44,2559.0,1.0,215.0,วิศวกรรมเครื่องกล,30.0,ภาควิชาวิศวกรรมเครื่องกล,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,218.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมเครื่องกล),หลักสูตรปกติ,R,ตกออก (พ้นสภาพการเป็นนักศึกษา),N,T,ช,ชาย,01,โครงการคัดเลือกนักเรียนใน 14 จังหวัดภาคใต้ เข...,1997-09-01,60.0,ยะลา,TH,THAILAND,โรงเรียนราชมุนีรังสฤษฏ์,56,ปัตตานี,21.00,1.0,Y,FT,N,N,2.50,2.94,3.25,3.47,3.27,3.23,3.47,0.0,3.31,3.73,0.00,0.0,3.77,ได้รับทุน,Y,ไม่พิการ,N,บิดาถึงแก่กรรม,6.0
4,rWseDSww8R,2559.0,1.0,235.0,วิศวกรรมเหมืองแร่,33.0,ภาควิชาวิศวกรรมเหมืองแร่และวัสดุ,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,240.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมเหมืองแร่),หลักสูตรปกติ,G,สำเร็จการศึกษา (พ้นสภาพการเป็นนักศึกษา),N,T,ช,ชาย,38,โครงการรับนักเรียนที่มีผลการเรียนดี,1997-10-05,63.0,สตูล,TH,THAILAND,โรงเรียนจุฬาภรณราชวิทยาลัย สตูล,63,สตูล,21.00,1.0,Y,FT,N,N,1.93,2.08,1.86,1.78,0.00,2.08,1.41,0.0,0.87,1.22,0.72,0.0,3.21,ไม่ได้รับทุน,N,ไม่พิการ,N,อยู่ด้วยกัน,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4115,mPcmlJsEow,2564.0,1.0,210.0,วิศวกรรมไฟฟ้า,28.0,ภาควิชาวิศวกรรมไฟฟ้า,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,213.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมไฟฟ้า),หลักสูตรปกติ,OK,กำลังศึกษา,Y,T,ช,ชาย,39,"โครงการ ""โควตาวิศวกรรมศาสตร์ มอ.""",2000-01-26,60.0,ยะลา,TH,THAILAND,โรงเรียนธรรมวิทยามูลนิธิ,60,ยะลา,22.50,1.0,N,FT,N,N,2.70,2.48,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,3.54,NaN,other,ไม่พิการ,N,อยู่ด้วยกัน,9.0
4116,IY8jWx00mt,2564.0,1.0,226.0,วิศวกรรมการผลิต,31.0,ภาควิชาวิศวกรรมอุตสาหการ,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,239.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมการผลิต),หลักสูตรปกติ,OK,กำลังศึกษา,Y,T,ช,ชาย,39,"โครงการ ""โควตาวิศวกรรมศาสตร์ มอ.""",2002-08-25,63.0,สตูล,TH,THAILAND,โรงเรียนควนโดนวิทยา,63,สตูล,37.50,1.0,N,FT,N,N,3.27,3.27,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,3.74,NaN,other,ไม่พิการ,N,อยู่ด้วยกัน,9.0
4117,uVfxDYkac8,2564.0,1.0,203.0,วิศวกรรมและการจัดการนวัตกรรม,193.0,คณะวิศวกรรมศาสตร์,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,4.0,ภาคปกติ (นานาชาติ),แผนการศึกษา ป.ตรี,254.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมและการจัดการนวัตก...,หลักสูตรนานาชาติ,OK,กำลังศึกษา,Y,T,ญ,หญิง,P4,โครงการคัดเลือกนักเรียนเข้าศึกษาในคณะวิศวกรรมศ...,2003-02-25,62.0,สงขลา,TH,THAILAND,โรงเรียนธิดานุเคราะห์,62,สงขลา,61.25,1.0,N,FT,Y,Y,2.56,3.15,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,3.25,NaN,other,ไม่พิการ,N,อยู่ด้วยกัน,9.0
4118,IcXALKhfPP,2564.0,1.0,203.0,วิศวกรรมและการจัดการนวัตกรรม,193.0,คณะวิศวกรรมศาสตร์,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,4.0,ภาคปกติ (นานาชาติ),แผนการศึกษา ป.ตรี,254.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมและการจัดการนวัตก...,หลักสูตรนานาชาติ,OK,กำลังศึกษา,Y,T,ช,ชาย,P4,โครงการคัดเลือกนักเรียนเข้าศึกษาในคณะวิศวกรรมศ...,1998-04-01,63.0,สตูล,TH,THAILAND,โรงเรียนดารุลมาอาเรฟมูลนิธิ,63,สตูล,21.25,1.0,N,FT,N,N,3.64,3.50,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,2.79,NaN,other,ไม่พิการ,N,มารดาถึงแก่กรรม,8.0
4119,q5SWpcypnh,2564.0,1.0,203.0,วิศวกรรมและการจัดการนวัตกรรม,193.0,คณะวิศวกรรมศาสตร์,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,4.0,ภาคปกติ (นานาชาติ),แผนการศึกษา ป.ตรี,254.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมและการจัดการนวัตก...,หลักสูตรนานาชาติ,OK,กำลังศึกษา,Y,T,ช,ชาย,P4,โครงการคัดเลือกนักเรียนเข้าศึกษาในคณะวิศวกรรมศ...,2003-01-30,54.0,นครศรีธรรมราช,TH,THAILAND,โรงเรียนปากพะยูนพิทยาคาร,58,พัทลุง,56.25,1.0,N,FT,N,N,3.17,2.78,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,3.26,ไม่ได้รับทุน,N,ไม่พิการ,N,อยู่ด้วยกัน,9.0

In [38]:
raw_datas = pd.read_csv('../data/data_dropout_59-64(1).csv')

In [39]:
d = raw_datas[raw_datas['ADMIT_YEAR'] == 2564]
raw_datas[raw_datas['ADMIT_YEAR'] == 2564].iloc[:,22:34].describe()

       STUD_BIRTH_PROVINCE_ID
count              713.000000
mean                55.183731
std                 12.891887
min                  1.000000
25%                 54.000000
50%                 58.000000
75%                 62.000000
max                 78.000000

In [40]:
raw_datas[(raw_datas['ADMIT_YEAR'] == 2564) & (raw_datas['เกรดปี2เทอม1'] == 0) ].describe()

,ADMIT_YEAR,ADMIT_TERM,MAJOR_ID,DEPT_ID,FAC_ID,STUDY_LEVEL_ID,STUDY_TYPE_ID,DEGREE_ID,STUD_BIRTH_PROVINCE_ID,ENG_SCORE,CAMPUS_ID,เกรดปี1เทอม1,เกรดปี1เทอม2,เกรดปี1เทอม3,เกรดปี2เทอม1,เกรดปี2เทอม2,เกรดปี2เทอม3,เกรดปี3เทอม1,เกรดปี3เทอม2,เกรดปี3เทอม3,เกรดปี4เทอม1,เกรดปี4เทอม2,เกรดปี4เทอม3,GPA_SCHOOL,PARENTS_MARRIED_NAME_CODE
count,712.0,712.0,712.000000,712.000000,712.0,712.0,712.000000,710.000000,712.000000,712.000000,712.0,712.000000,712.000000,712.000000,712.0,712.0,712.0,712.0,712.0,712.0,712.0,712.0,712.0,712.000000,712.000000
mean,2564.0,1.0,223.804775,44.021067,6.0,6.0,1.084270,222.326761,55.171348,35.116222,1.0,3.071503,3.090688,0.137275,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.416994,8.494382
std,0.0,0.0,14.896637,44.440334,0.0,0.0,0.496037,27.573014,12.896706,13.654708,0.0,0.609670,0.875186,0.692263,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.332375,1.901209
min,2564.0,1.0,200.000000,28.000000,6.0,6.0,1.000000,149.000000,1.000000,0.000000,1.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.000000
25%,2564.0,1.0,214.000000,29.000000,6.0,6.0,1.000000,213.000000,54.000000,25.000000,1.0,2.847500,2.950000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.240000,9.000000
50%,2564.0,1.0,220.000000,31.000000,6.0,6.0,1.000000,228.000000,58.000000,32.500000,1.0,3.180000,3.360000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.440000,9.000000
75%,2564.0,1.0,230.000000,33.000000,6.0,6.0,1.000000,243.000000,62.000000,41.250000,1.0,3.450000,3.590000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.640000,9.000000
max,2564.0,1.0,254.000000,193.000000,6.0,6.0,4.000000,254.000000,78.000000,85.000000,1.0,4.000000,4.000000,4.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.000000,10.000000

In [41]:
(2.61+3.00)/2

2.8049999999999997

In [42]:
for i in raw_datas[(raw_datas['ADMIT_YEAR'] == 2562)]['เกรดปี2เทอม3']:
    print(i)

2.77
1.75
3.02
0.0
2.92
3.55
3.46
3.79
3.43
3.01
3.62
0.0
2.0
2.55
2.04
2.34
2.96
3.22
2.62
3.0
3.5
2.72
3.37
2.68
0.0
2.25
3.25
3.12
2.82
3.0
3.35
3.42
3.67
1.73
3.79
3.52
2.77
2.44
3.05
3.78
2.94
2.78
3.65
2.85
3.45
3.8
3.56
2.62
3.31
3.37
3.65
2.98
2.52
3.06
2.36
3.09
3.62
2.65
2.15
3.43
2.6
3.54
2.25
3.04
3.47
2.4
3.06
1.53
3.4
3.45
2.87
3.38
2.73
3.57
2.88
3.7
2.88
3.0
3.56
0.0
1.93
0.0
3.5
2.15
2.28
3.16
3.22
3.02
3.11
2.2
3.14
3.52
0.96
3.15
2.87
1.57
3.2
3.22
1.59
1.59
3.68
3.34
0.0
3.56
3.4
2.56
3.13
2.47
3.44
3.16
2.84
2.92
0.0
2.72
2.68
2.65
3.15
2.89
2.66
2.14
2.72
3.52
0.0
2.9
0.0
3.08
3.33
2.12
0.0
3.6
3.15
3.54
3.06
2.73
3.4
3.26
3.45
2.2
3.93
3.04
3.12
2.79
3.03
3.25
0.0
2.7
3.11
2.44
3.15
2.74
2.58
3.29
3.59
0.0
2.75
2.42
2.66
3.5
2.54
2.86
2.69
2.54
3.55
3.03
2.53
3.2
3.68
2.97
2.39
3.5
0.0
3.58
2.9
2.72
2.5
3.04
2.44
3.79
2.85
3.02
3.25
3.18
2.14
3.5
3.31
4.0
3.52
3.78
3.45
2.45
0.0
3.77
3.22
2.71
3.54
2.2
3.42
3.5
3.08
2.88
3.45
2.91
3.87
2.16
4.0
2.57
2.58
3.61
0.0
2.25
3.0
2.59
3.33
3.3
3.06
3.38
2.4
3.09
3.5
3.51
3.28
2.98
2.75
3.43
3.41
2.71
0.0
3.34
3.6
2.71
2.79
2.16
2.73
3.93
2.15
2.78
2.6
2.71
2.72
3.13
0.0
2.26
2.45
3.5
3.64
2.52
2.63
2.56
2.83
3.63
2.75
3.37
2.87
2.11
2.97
2.46
0.0
3.16
2.76
2.92
2.61
3.19
3.21
2.35
2.75
2.85
3.66
2.58
3.52
3.29
3.54
3.52
3.8
3.54
3.3
2.59
3.5
3.3
3.22
3.11
2.42
3.12
3.11
3.71
3.35
2.81
3.3
3.69
2.81
3.59
3.42
3.26
2.44
3.25
3.43
3.66
3.18
2.61
0.0
1.44
2.19
2.52
2.62
2.24
2.72
2.88
3.78
1.25
2.92
3.16
4.0
2.7
3.92
2.92
3.5
2.47
2.75
3.45
3.57
2.33
3.14
3.47
3.37
3.48
3.54
3.65
3.28
2.44
3.28
2.73
2.72
3.4
3.11
2.85
3.7
2.69
3.13
2.61
3.38
2.38
3.25
1.73
3.5
3.47
2.93
3.82
3.3
2.29
2.53
2.16
3.43
3.18
3.42
3.13
2.91
3.17
2.8
2.22
3.14
2.76
0.0
2.21
3.52
2.14
3.33
3.01
3.64
3.33
2.04
2.66
2.64
3.0
2.41
0.0
2.97
3.23
2.95
3.22
2.56
1.98
1.91
3.55
3.26
2.76
3.73
3.45
1.94
2.1
0.8
1.95
3.06
4.0
3.27
2.74
3.18
3.28
3.5
2.95
2.68
0.0
3.52
3.0
3.16
2.16
2.12
0.0
3.83
3.18
2.8
1.81
2.87
2.79
3.62
2.02
2.39
2.98
2.87
1.68
1.89
2.69
2.4
2.7
3.0
2.87
2.5
2.26
0.0
0.94
2.47
3.52
2.02
2.07
2.78
3.1
3.11
3.61
3.3
3.18
2.66
0.0
2.72
0.0
1.78
1.8
2.8
2.16
2.3
3.06
2.15
0.0
2.94
3.0
0.0
0.0
2.77
3.25
2.45
2.96
2.45
2.83
3.38
2.0
2.48
2.59
2.5
2.72
1.89
3.6
2.43
3.38
1.86
3.23
0.0
2.85
3.08
2.5
2.88
3.0
2.61
2.91
2.36
2.21
2.25
0.0
0.0
2.67
3.43
3.0
2.3
2.42
3.16
1.75
3.25
3.65
2.34
2.17
2.77
2.9
2.89
3.68
2.81
2.57
3.1
2.38
2.22
2.85
2.71
2.64
2.81
3.13
2.7
3.39
3.38
2.75
0.0
2.17
2.31
3.64
3.5
3.39
3.21
0.0
3.5
3.57
2.63
3.45
2.95
0.0
3.05
3.02
3.4
2.82
2.66
2.61
3.78
3.86
2.52
3.04
2.93
3.19
2.58
3.22
3.08
3.02
4.0
2.56
3.3
3.52
4.0
3.5
2.62
3.55
0.0
2.6
2.7
2.79
2.72
2.92
3.22
3.12
2.43
3.26
2.36
2.68
1.84
3.12
3.25
3.54
2.54
3.02
3.33
2.62
3.35
2.29
2.37
2.45
2.94
2.18
3.31
3.18
2.13
3.18
2.58
3.75
3.09
2.02
1.95
2.88
2.68
3.66
2.62
3.58
3.83
2.5
3.58
2.97
0.0
0.0
1.52
0.0
3.43
2.71
3.07
3.32
3.75
0.0
3.23
3.0
2.38
4.0
3.0
3.28
1.97
2.0
0.0
3.66
3.65
3.16
3.6
3.19
0.0
3.38
3.35
3.21
3.14
2.97
1.95
3.15
3.44
0.89
2.34
3.02
2.07
0.0
3.2
3.86
2.71
2.67
2.75
3.1
3.05
3.65
0.0
3.87
3.73
2.97
3.27
2.46
1.5
3.5
2.3
2.78
0.0
3.0
0.0
2.77
2.46
2.06
3.11
0.0
3.7
2.38
0.0
2.6
3.54
0.0
2.76
2.85
2.64
3.5
3.56
2.67
2.7
2.67
1.7
2.7
0.0
1.9
2.31
1.5
1.77

In [43]:
raw_datas[(raw_datas['ADMIT_YEAR'] == 2563) & (raw_datas['เกรดปี1เทอม3'] != 0) ].describe()

,ADMIT_YEAR,ADMIT_TERM,MAJOR_ID,DEPT_ID,FAC_ID,STUDY_LEVEL_ID,STUDY_TYPE_ID,DEGREE_ID,STUD_BIRTH_PROVINCE_ID,ENG_SCORE,CAMPUS_ID,เกรดปี1เทอม1,เกรดปี1เทอม2,เกรดปี1เทอม3,เกรดปี2เทอม1,เกรดปี2เทอม2,เกรดปี2เทอม3,เกรดปี3เทอม1,เกรดปี3เทอม2,เกรดปี3เทอม3,เกรดปี4เทอม1,เกรดปี4เทอม2,เกรดปี4เทอม3,GPA_SCHOOL,PARENTS_MARRIED_NAME_CODE
count,639.0,639.0,639.000000,639.000000,639.0,639.0,639.0,603.000000,639.000000,639.000000,639.0,639.000000,639.000000,639.000000,639.000000,639.000000,639.000000,639.000000,639.0,639.0,639.0,639.0,639.0,639.000000,639.000000
mean,2563.0,1.0,222.682316,39.898279,6.0,6.0,1.0,230.029851,56.097027,34.611502,1.0,2.748717,2.488842,2.846776,2.901659,0.492019,0.082676,0.004116,0.0,0.0,0.0,0.0,0.0,3.139171,8.391236
std,0.0,0.0,13.063776,37.486725,0.0,0.0,0.0,11.359386,12.119053,12.380842,0.0,0.483129,0.478083,0.666955,0.641836,1.110259,0.531416,0.104041,0.0,0.0,0.0,0.0,0.0,0.320245,1.975632
min,2563.0,1.0,200.000000,28.000000,6.0,6.0,1.0,211.000000,1.000000,0.000000,1.0,1.110000,0.790000,0.110000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,2.080000,1.000000
25%,2563.0,1.0,214.500000,29.000000,6.0,6.0,1.0,218.000000,54.000000,26.250000,1.0,2.420000,2.140000,2.500000,2.650000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,2.925000,9.000000
50%,2563.0,1.0,220.000000,31.000000,6.0,6.0,1.0,233.000000,60.000000,32.500000,1.0,2.780000,2.520000,2.940000,3.020000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,3.140000,9.000000
75%,2563.0,1.0,230.000000,33.000000,6.0,6.0,1.0,240.000000,62.000000,41.250000,1.0,3.060000,2.800000,3.270000,3.320000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,3.330000,9.000000
max,2563.0,1.0,250.000000,193.000000,6.0,6.0,1.0,245.000000,71.000000,93.750000,1.0,4.000000,3.850000,4.000000,4.000000,4.000000,4.000000,2.630000,0.0,0.0,0.0,0.0,0.0,3.970000,11.000000

In [44]:
raw_datas = raw_datas.drop([3407])

In [45]:
raw_datas[(raw_datas['ADMIT_YEAR'] == 2564)]

,STUDENT_ID,ADMIT_YEAR,ADMIT_TERM,MAJOR_ID,MAJOR_NAME_THAI,DEPT_ID,DEPT_NAME_THAI,FAC_ID,FAC_NAME_THAI,STUDY_LEVEL_ID,STUDY_LEVEL_NAME,STUDY_TYPE_ID,STUDY_TYPE_NAME,STUDY_PLAN_NAME,DEGREE_ID,COURSE_NAME,COURSE_DEGREE,COURSE_TYPE_NAME,STUDY_STATUS,STATUS_DESC_THAI,STILL_STUDENT,NATIONALITY,SEX_SHORT_NAME_THAI,SEX_NAME_THAI,ENT_METHOD,ENT_METHOD_DESC,STUD_BIRTH_DATE,STUD_BIRTH_PROVINCE_ID,PROVINCE_NAME_THAI,BIRTH_COUNTRY,COUNTRY_NAME_ENG,PREV_INSTITUTION_NAME,INSTITUTION_PROVINCE_ID,INSTITUTION_PROVINCE_NAME,ENG_SCORE,CAMPUS_ID,CAMPUS_NAME_THAI,IS_GRAD_IN_COURSE,CURR_REG,IN_PROVINCE,IN_PROVINCE_CAMPUS,เกรดปี1เทอม1,เกรดปี1เทอม2,เกรดปี1เทอม3,เกรดปี2เทอม1,เกรดปี2เทอม2,เกรดปี2เทอม3,เกรดปี3เทอม1,เกรดปี3เทอม2,เกรดปี3เทอม3,เกรดปี4เทอม1,เกรดปี4เทอม2,เกรดปี4เทอม3,GPA_SCHOOL,FUND_NAME,FUND_NAME_CODE,DEFORMITY_NAME,DEFORMITY_NAME_code,PARENTS_MARRIED_NAME,PARENTS_MARRIED_NAME_CODE
3408,WYwwOfyF1f,2564.0,1.0,210.0,วิศวกรรมไฟฟ้า,28.0,ภาควิชาวิศวกรรมไฟฟ้า,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,213.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมไฟฟ้า),หลักสูตรปกติ,OK,กำลังศึกษา,Y,T,ญ,หญิง,38,โครงการรับนักเรียนที่มีผลการเรียนดี,2002-07-27,64.0,สุราษฎร์ธานี,TH,THAILAND,โรงเรียนสุราษฎร์ธานี 2,64,สุราษฎร์ธานี,41.25,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,3.44,3.15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.60,NaN,other,ไม่พิการ,N,บิดาและมารดาแต่งงานใหม่,4.0
3409,rowK5jcAfa,2564.0,1.0,220.0,วิศวกรรมโยธา,29.0,ภาควิชาวิศวกรรมโยธา,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,223.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมโยธา),หลักสูตรปกติ,OK,กำลังศึกษา,Y,T,ช,ชาย,38,โครงการรับนักเรียนที่มีผลการเรียนดี,2002-09-23,53.0,ตรัง,TH,THAILAND,NaN,53,ตรัง,26.25,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,3.06,3.44,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.40,NaN,other,ไม่พิการ,N,อยู่ด้วยกัน,9.0
3410,GUee5TYTB3,2564.0,1.0,240.0,วิศวกรรมคอมพิวเตอร์,34.0,ภาควิชาวิศวกรรมคอมพิวเตอร์,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,243.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมคอมพิวเตอร์),หลักสูตรปกติ,OK,กำลังศึกษา,Y,T,ญ,หญิง,38,โครงการรับนักเรียนที่มีผลการเรียนดี,2002-09-18,52.0,ชุมพร,TH,THAILAND,โรงเรียนสอาดเผดิมวิทยา,52,ชุมพร,40.00,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,3.50,3.28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.80,NaN,other,ไม่พิการ,N,อยู่ด้วยกัน,9.0
3411,5CybVIozAm,2564.0,1.0,240.0,วิศวกรรมคอมพิวเตอร์,34.0,ภาควิชาวิศวกรรมคอมพิวเตอร์,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,243.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมคอมพิวเตอร์),หลักสูตรปกติ,OK,กำลังศึกษา,Y,T,ญ,หญิง,38,โครงการรับนักเรียนที่มีผลการเรียนดี,2003-01-04,53.0,ตรัง,TH,THAILAND,โรงเรียนย่านตาขาวรัฐชนูปถัมภ์,53,ตรัง,42.50,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,2.90,3.54,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.58,ไม่ได้รับทุน,N,ไม่พิการ,N,หย่าร้าง,10.0
3412,EvX0Ym7aR3,2564.0,1.0,254.0,วิศวกรรมเหมืองแร่และวัสดุ,33.0,ภาควิชาวิศวกรรมเหมืองแร่และวัสดุ,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,149.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมเหมืองแร่และวัสดุ),หลักสูตรปกติ,E,ลาออก (พ้นสภาพการเป็นนักศึกษา),N,T,ญ,หญิง,38,โครงการรับนักเรียนที่มีผลการเรียนดี,2002-03-25,62.0,สงขลา,TH,THAILAND,โรงเรียนนาทวีวิทยาคม,62,สงขลา,42.50,1.0,วิทยาเขตหาดใหญ่,N,FT,Y,Y,2.97,3.52,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.79,NaN,other,ไม่พิการ,N,อยู่ด้วยกัน,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4115,mPcmlJsEow,2564.0,1.0,210.0,วิศวกรรมไฟฟ้า,28.0,ภาควิชาวิศวกรรมไฟฟ้า,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,213.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมไฟฟ้า),หลักสูตรปกติ,OK,กำลังศึกษา,Y,T,ช,ชาย,39,"โครงการ ""โควตาวิศวกรรมศาสตร์ มอ.""",2000-01-26,60.0,ยะลา,TH,THAILAND,โรงเรียนธรรมวิทยามูลนิธิ,60,ยะลา,22.50,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,2.70,2.48,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.54,NaN,other,ไม่พิการ,N,อยู่ด้วยกัน,9.0
4116,IY8jWx00mt,2564.0,1.0,226.0,วิศวกรรมการผลิต,31.0,ภาควิชาวิศวกรรมอุตสาหการ,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,239.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมการผลิต),หลักสูตรปกติ,OK,กำลังศึกษา,Y,T,ช,ชาย,39,"โครงการ ""โควตาวิศวกรรมศาสตร์ มอ.""",2002-08-25,63.0,สตูล,TH,THAILAND,โรงเรียนควนโดนวิทยา,63,สตูล,37.50,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,3.27,3.27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.74,NaN,other,ไม่พิการ,N,อยู่ด้วยกัน,9.0
4117,uVfxDYkac8,2564.0,1.0,203.0,วิศวกรรมและการจัดการนวัตกรรม,193.0,คณะวิศวกรรมศาสตร์,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,4.0,ภาคปกติ (นานาชาติ),แผนการศึกษา ป.ตรี,254.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมและการจัดการนวัตก...,หลักสูตรนานาชาติ,OK,กำลังศึกษา,Y,T,ญ,หญิง,P4,โครงการคัดเลือกนักเรียนเข้าศึกษาในคณะวิศวกรรมศ...,2003-02-25,62.0,สงขลา,TH,THAILAND,โรงเรียนธิดานุเคราะห์,62,สงขลา,61.25,1.0,วิทยาเขตหาดใหญ่,N,FT,Y,Y,2.56,3.15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.25,NaN,other,ไม่พิการ,N,อยู่ด้วยกัน,9.0
4118,IcXALKhfPP,2564.0,1.0,203.0,วิศวกรรมและการจัดการนวัตกรรม,193.0,คณะวิศวกรรมศาสตร์,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,4.0,ภาคปกติ (นานาชาติ),แผนการศึกษา ป.ตรี,254.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมและการจัดการนวัตก...,หลักสูตรนานาชาติ,OK,กำลังศึกษา,Y,T,ช,ชาย,P4,โครงการคัดเลือกนักเรียนเข้าศึกษาในคณะวิศวกรรมศ...,1998-04-01,63.0,สตูล,TH,THAILAND,โรงเรียนดารุลมาอาเรฟมูลนิธิ,63,สตูล,21.25,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,3.64,3.50,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.79,NaN,other,ไม่พิการ,N,มารดาถึงแก่กรรม,8.0
4119,q5SWpcypnh,2564.0,1.0,203.0,วิศวกรรมและการจัดการนวัตกรรม,193.0,คณะวิศวกรรมศาสตร์,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,4.0,ภาคปกติ (นานาชาติ),แผนการศึกษา ป.ตรี,254.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมและการจัดการนวัตก...,หลักสูตรนานาชาติ,OK,กำลังศึกษา,Y,T,ช,ชาย,P4,โครงการคัดเลือกนักเรียนเข้าศึกษาในคณะวิศวกรรมศ...,2003-01-30,54.0,นครศรีธรรมราช,TH,THAILAND,โรงเรียนปากพะยูนพิทยาคาร,58,พัทลุง,56.25,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,3.17,2.78,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.26,ไม่ได้รับทุน,N,ไม่พิการ,N,อยู่ด้วยกัน,9.0

In [46]:
raw_datas[(raw_datas['STUDY_STATUS'] != "OK") & (raw_datas['STUDY_STATUS'] != "R") & (raw_datas['STUDY_STATUS'] != "G") & (raw_datas['STUDY_STATUS'] != "E")]

,STUDENT_ID,ADMIT_YEAR,ADMIT_TERM,MAJOR_ID,MAJOR_NAME_THAI,DEPT_ID,DEPT_NAME_THAI,FAC_ID,FAC_NAME_THAI,STUDY_LEVEL_ID,STUDY_LEVEL_NAME,STUDY_TYPE_ID,STUDY_TYPE_NAME,STUDY_PLAN_NAME,DEGREE_ID,COURSE_NAME,COURSE_DEGREE,COURSE_TYPE_NAME,STUDY_STATUS,STATUS_DESC_THAI,STILL_STUDENT,NATIONALITY,SEX_SHORT_NAME_THAI,SEX_NAME_THAI,ENT_METHOD,ENT_METHOD_DESC,STUD_BIRTH_DATE,STUD_BIRTH_PROVINCE_ID,PROVINCE_NAME_THAI,BIRTH_COUNTRY,COUNTRY_NAME_ENG,PREV_INSTITUTION_NAME,INSTITUTION_PROVINCE_ID,INSTITUTION_PROVINCE_NAME,ENG_SCORE,CAMPUS_ID,CAMPUS_NAME_THAI,IS_GRAD_IN_COURSE,CURR_REG,IN_PROVINCE,IN_PROVINCE_CAMPUS,เกรดปี1เทอม1,เกรดปี1เทอม2,เกรดปี1เทอม3,เกรดปี2เทอม1,เกรดปี2เทอม2,เกรดปี2เทอม3,เกรดปี3เทอม1,เกรดปี3เทอม2,เกรดปี3เทอม3,เกรดปี4เทอม1,เกรดปี4เทอม2,เกรดปี4เทอม3,GPA_SCHOOL,FUND_NAME,FUND_NAME_CODE,DEFORMITY_NAME,DEFORMITY_NAME_code,PARENTS_MARRIED_NAME,PARENTS_MARRIED_NAME_CODE
560,VaAo6ea9xp,2559.0,1.0,200.0,ยังไม่แยกสาขาวิชา,193.0,คณะวิศวกรรมศาสตร์,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,NaN,NaN,รอระบุหลักสูตร,รอระบุหลักสูตร,NaN,I,เสียชีวิต (พ้นสภาพการเป็นนักศึกษา),N,T,ญ,หญิง,36,Admission,1997-05-21,31.0,นครราชสีมา,TH,THAILAND,โรงเรียนเตรียมอุดมศึกษาพัฒนาการ ลำลูกกา,04,ปทุมธานี,34.00,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,2.67,2.17,3.50,2.05,1.75,4.00,2.08,2.82,0.00,3.23,3.31,0.0,3.46,ไม่ได้รับทุน,N,ไม่พิการ,N,อยู่ด้วยกัน,9.0
1207,E4Y27ycnkg,2560.0,1.0,235.0,วิศวกรรมเหมืองแร่,33.0,ภาควิชาวิศวกรรมเหมืองแร่และวัสดุ,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,240.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมเหมืองแร่),หลักสูตรปกติ,D,ลาพักการศึกษา,Y,T,ช,ชาย,36,Admission,1998-12-28,50.0,สมุทรปราการ,TH,THAILAND,โรงเรียนอบจ.เมืองภูเก็ต,59,ภูเก็ต,27.50,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,1.52,3.50,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,3.23,ไม่ได้รับทุน,N,ไม่พิการ,N,อยู่ด้วยกัน,9.0
1371,wGX1SYgFqb,2560.0,1.0,240.0,วิศวกรรมคอมพิวเตอร์,34.0,ภาควิชาวิศวกรรมคอมพิวเตอร์,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,243.0,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมคอมพิวเตอร์),วิศวกรรมศาสตรบัณฑิต (วิศวกรรมคอมพิวเตอร์),หลักสูตรปกติ,D,ลาพักการศึกษา,Y,T,ช,ชาย,01,สอบตรง(รับตรง 14 จังหวัดภาคใต้),1998-06-23,1.0,กรุงเทพมหานคร,TH,THAILAND,โรงเรียนกาญจนาภิเษกวิทยาลัย กระบี่,51,กระบี่,0.00,3.0,วิทยาเขตภูเก็ต,N,FT,N,N,2.57,2.30,1.18,1.61,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,2.55,ไม่ได้รับทุน,N,ไม่พิการ,N,อยู่ด้วยกัน,9.0
1379,vY1GheP1tE,2560.0,1.0,240.0,วิศวกรรมคอมพิวเตอร์,34.0,ภาควิชาวิศวกรรมคอมพิวเตอร์,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,243.0,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมคอมพิวเตอร์),วิศวกรรมศาสตรบัณฑิต (วิศวกรรมคอมพิวเตอร์),หลักสูตรปกติ,D,ลาพักการศึกษา,Y,T,ญ,หญิง,01,สอบตรง(รับตรง 14 จังหวัดภาคใต้),1999-02-07,62.0,สงขลา,TH,THAILAND,โรงเรียน มอ.วิทยานุสรณ์ สุราษฎร์ธานี,64,สุราษฎร์ธานี,0.00,3.0,วิทยาเขตภูเก็ต,N,FT,N,N,3.25,1.97,1.00,2.34,2.00,1.11,1.91,2.00,2.01,3.00,1.67,2.4,3.80,ไม่ได้รับทุน,N,ไม่พิการ,N,บิดาถึงแก่กรรม,6.0
1385,6mQv9GfwUZ,2560.0,1.0,240.0,วิศวกรรมคอมพิวเตอร์,34.0,ภาควิชาวิศวกรรมคอมพิวเตอร์,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,243.0,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมคอมพิวเตอร์),วิศวกรรมศาสตรบัณฑิต (วิศวกรรมคอมพิวเตอร์),หลักสูตรปกติ,D,ลาพักการศึกษา,Y,T,ช,ชาย,01,สอบตรง(รับตรง 14 จังหวัดภาคใต้),1998-11-06,53.0,ตรัง,TH,THAILAND,โรงเรียนสภาราชินี จังหวัดตรัง,53,ตรัง,0.00,3.0,วิทยาเขตภูเก็ต,N,FT,N,N,0.65,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,2.26,ไม่ได้รับทุน,N,ไม่พิการ,N,อยู่ด้วยกัน,9.0
1576,rRGjDvQXks,2561.0,1.0,240.0,วิศวกรรมคอมพิวเตอร์,34.0,ภาควิชาวิศวกรรมคอมพิวเตอร์,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,243.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมคอมพิวเตอร์),หลักสูตรปกติ,D,ลาพักการศึกษา,Y,T,ช,ชาย,25,โครงการดาวรุ่งคอมพิวเตอร์,1999-11-01,62.0,สงขลา,TH,THAILAND,โรงเรียนแสงทองวิทยา,62,สงขลา,35.00,1.0,วิทยาเขตหาดใหญ่,N,FT,Y,Y,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,2.65,ไม่ได้รับทุน,N,ไม่พิการ,N,อยู่ด้วยกัน,9.0
1711,A8m0PfLqgf,2561.0,1.0,205.0,วิศวกรรมสิ่งแวดล้อม,29.0,ภาควิชาวิศวกรรมโยธา,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,245.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมสิ่งแวดล้อม),หลักสูตรปกติ,D,ลาพักการศึกษา,Y,T,ช,ชาย,38,โครงการรับนักเรียนที่มีผลการเรียนดี,1999-05-27,62.0,สงขลา,TH,THAILAND,โรงเรียนหาดใหญ่วิทยาลัยสมบูรณ์กุลกันยา,62,สงขลา,38.75,1.0,วิทยาเขตหาดใหญ่,N,FT,Y,Y,2.87,2.06,3.25,2.65,2.78,3.50,2.66,2.69,0.00,3.28,3.31,0.0,2.88,ไม่ได้รับทุน,N,ไม่พิการ,N,อยู่ด้วยกัน,9.0
1831,QYVCzH69WH,2561.0,1.0,215.0,วิศวกรรมเครื่องกล,30.0,ภาควิชาวิศวกรรมเครื่องกล,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,218.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมเครื่องกล),หลักสูตรปกติ,D,ลาพักการศึกษา,Y,T,ช,ชาย,01,โครงการคัดเลือกนักเรียนใน 14 จังหวัดภาคใต้ เข...,1999-08-20,62.0,สงขลา,TH,THAILAND,โรงเรียนมอ. วิทยานุสรณ์,62,สงขลา,46.25,1.0,วิทยาเขตหาดใหญ่,N,FT,Y,Y,2.18,2.07,0.00,1.96,2.02,2.73,2.75,3.00,3.01,3.20,0.00,0.0,2.73,ไม่ได้รับทุน,N,ไม่พิการ,N,อยู่ด้วยกัน,9.0
2045,b6zDM0waat,2562.0,1.0,210.0,วิศวกรรมไฟฟ้า,28.0,ภาควิชาวิศวกรรมไฟฟ้า,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,213.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมไฟฟ้า),หลักสูตรปกติ,I,เสียชีวิต (พ้นสภาพการเป็นนักศึกษา),N,T,ญ,หญิง,39,"โครงการ ""โควตาวิศวกรรมศาสตร์ มอ.""",2000-03-20,62.0,สงขลา,TH,THAILAND,โรงเรียนวรนารีเฉลิม จังหวัดสงขลา,62,สงขลา,22.50,1.0,วิทยาเขตหาดใหญ่,N,FT,Y,Y,3.78,3.60,3.87,3.10,3.33,3.62,3.75,0.00,0.00,0.00,0.00,0.0,2.71,ไม่ได้รับทุน,N,ไม่พิการ,N,อยู่ด้วยกัน,9.0
2331,JGFt8lej0w,2562.0,1.0,240.0,วิศวกรรมคอมพิวเตอร์,34.0,ภาควิชาวิศวกรรมคอมพิวเตอร์,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,243.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมคอมพิวเตอร์),หลักสูตรปกติ,D,ลาพักการศึกษา,Y,T,ช,ชาย,01,โครงการคัดเลือกนักเรียนใน 14 จังหวัดภาคใต้ เข...,2001-04-12,54.0,นครศรีธรรมราช,TH,THAILAND,โรงเรียนสวีวิทยา,52,ชุมพร,58.75,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,2.82,2.93,2.38,2.90,3.15,3.18,0.00,0.00,0.00,0.00,0.00,0.0,3.28,ไม่ได้รับทุน,N,ไม่พิการ,N,อยู่ด้วยกัน,9.0
2872,T2Ic3r974k,2563.0,1.0,215.0,วิศวกรรมเครื่องกล,30.0,ภาควิชาวิศวกรรมเครื่องกล,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,218.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมเครื่องกล),หลักสูตรปกติ,D,ลาพักการศึกษา,Y,T,ช,ชาย,36,Admission,2001-09-18,62.0,สงขลา,TH,THAILAND,โรงเรียนเบญจมราชูทิศ,54,นครศรีธรรมราช,46.25,1.0,วิทยาเขตหาดใหญ่,N,FT,Y,N,2.84,2.09,2.52,3.37,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,2.71,ไม่ได้รับทุน,N,ไม่พิการ,N,หย่าร้าง,10.0
3057,sBpHoqV9at,2563.0,1.0,220.0,วิศวกรรมโยธา,29.0,ภาควิชาวิศวกรรมโยธา,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,223.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมโยธา),หลักสูตรปกติ,I,เสียชีวิต (พ้นสภาพการเป็นนักศึกษา),N,T,ช,ชาย,36,Admission,2001-10-24,62.0,สงขลา,TH,THAILAND,โรงเรียนหาดใหญ่วิทยาลัยสมบูรณ์กุลกันยา,62,สงขลา,36.25,1.0,วิทยาเขตหาดใหญ่,N,FT,Y,Y,3.02,2.83,3.34,3.31,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,2.86,ไม่ได้รับทุน,N,ไม่พิการ,N,อยู่ด้วยกัน,9.0
3669,yISuOHmAnH,2564.0,1.0,220.0,วิศวกรรมโยธา,29.0,ภาควิชาวิศวกรรมโยธา,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,223.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมโยธา),หลักสูตรปกติ,D,ลาพักการศึกษา,Y,T,ช,ชาย,38,โครงการรับนักเรียนที่มีผลการเรียนดี,2002-10-01,56.0,ปัตตานี,TH,THAILAND,โรงเรียนสามารถดีวิทยา,56,ปัตตานี,33.75,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,2.43,2.57,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,3.41,NaN,other,ไม่พิการ,N,อยู่ด้วยกัน,9.0
3758,0VcN5x7DjR,2564.0,1.0,240.0,วิศวกรรมคอมพิวเตอร์,34.0,ภาควิชาวิศวกรรมคอมพิวเตอร์,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,243.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมคอมพิวเตอร์),หลักสูตรปกติ,D,ลาพักการศึกษา,Y,T,ญ,หญิง,38,โครงการรับนักเรียนที่มีผลการเรียนดี,2001-09-20,54.0,นครศรีธรรมราช,TH,THAILAND,โรงเรียนมุสลิมสันติธรรมมูลนิธิ,54,นครศรีธรรมราช,32.50,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,3.73,3.48,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,3.29,NaN,other,ไม่พิการ,N,อยู่ด้วยกัน,9.0

In [47]:
raw_datas['STUDY_STATUS'].unique()

array(['G', 'E', 'R', 'OK', 'I', 'D'], dtype=object)

In [48]:
raw_datas = raw_datas[(raw_datas['STUDY_STATUS'] != "I") & (raw_datas['STUDY_STATUS'] != "D")]

In [49]:
raw_datas['STUDY_STATUS'].unique()

array(['G', 'E', 'R', 'OK'], dtype=object)

In [50]:
(raw_datas[(raw_datas['เกรดปี1เทอม3'] != 0)]['STUDY_STATUS'] == 'R').sum()

174

In [51]:
(raw_datas[(raw_datas['เกรดปี1เทอม3'] == 0)]).describe()

,ADMIT_YEAR,ADMIT_TERM,MAJOR_ID,DEPT_ID,FAC_ID,STUDY_LEVEL_ID,STUDY_TYPE_ID,DEGREE_ID,STUD_BIRTH_PROVINCE_ID,ENG_SCORE,CAMPUS_ID,เกรดปี1เทอม1,เกรดปี1เทอม2,เกรดปี1เทอม3,เกรดปี2เทอม1,เกรดปี2เทอม2,เกรดปี2เทอม3,เกรดปี3เทอม1,เกรดปี3เทอม2,เกรดปี3เทอม3,เกรดปี4เทอม1,เกรดปี4เทอม2,เกรดปี4เทอม3,GPA_SCHOOL,PARENTS_MARRIED_NAME_CODE
count,972.000000,972.0,972.000000,972.000000,972.0,972.0,972.000000,949.000000,972.000000,972.000000,972.000000,972.000000,972.000000,972.0,972.000000,972.000000,972.000000,972.000000,972.000000,972.000000,972.000000,972.000000,972.000000,972.000000,972.000000
mean,2563.004115,1.0,224.252058,43.814815,6.0,6.0,1.061728,224.970495,55.623457,33.497171,1.067901,2.682027,2.454527,0.0,0.074660,0.074249,0.084794,0.052387,0.054928,0.054023,0.052335,0.031029,0.038056,3.329877,8.433128
std,1.715617,0.0,14.615189,43.826320,0.0,0.0,0.426100,24.628959,12.349952,14.568893,0.362391,0.912460,1.330359,0.0,0.404554,0.429169,0.499260,0.337816,0.373461,0.382647,0.360415,0.272404,0.343794,0.376183,1.967986
min,2559.000000,1.0,200.000000,28.000000,6.0,6.0,1.000000,149.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,2563.000000,1.0,214.000000,29.000000,6.0,6.0,1.000000,218.000000,54.000000,24.750000,1.000000,2.150000,1.520000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.147500,9.000000
50%,2564.000000,1.0,225.000000,31.000000,6.0,6.0,1.000000,228.000000,58.000000,31.250000,1.000000,2.950000,3.060000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.370000,9.000000
75%,2564.000000,1.0,240.000000,33.000000,6.0,6.0,1.000000,243.000000,62.000000,41.250000,1.000000,3.352500,3.500000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.590000,9.000000
max,2564.000000,1.0,254.000000,193.000000,6.0,6.0,4.000000,254.000000,78.000000,88.750000,3.000000,4.000000,4.000000,0.0,3.690000,3.620000,4.000000,3.730000,4.000000,4.000000,3.660000,4.000000,4.000000,4.000000,10.000000

In [52]:
(raw_datas["STUDY_STATUS"] == 'R').sum()

214

In [53]:
174/214

0.8130841121495327

In [54]:
40/214

0.18691588785046728

In [55]:
1345/1483

0.9069453809844908

In [56]:
1483-138

1345

In [57]:
raw_datas['ADMIT_YEAR']

0       2559.0
1       2559.0
2       2559.0
3       2559.0
4       2559.0
         ...
4115    2564.0
4116    2564.0
4117    2564.0
4118    2564.0
4119    2564.0
Name: ADMIT_YEAR, Length: 4105, dtype: float64

In [58]:
(raw_datas['เกรดปี1เทอม3'] != 0).sum()

3133

In [59]:
raw_datas = raw_datas.drop(['DEFORMITY_NAME'],axis=1)

In [60]:
raw_datas

,STUDENT_ID,ADMIT_YEAR,ADMIT_TERM,MAJOR_ID,MAJOR_NAME_THAI,DEPT_ID,DEPT_NAME_THAI,FAC_ID,FAC_NAME_THAI,STUDY_LEVEL_ID,STUDY_LEVEL_NAME,STUDY_TYPE_ID,STUDY_TYPE_NAME,STUDY_PLAN_NAME,DEGREE_ID,COURSE_NAME,COURSE_DEGREE,COURSE_TYPE_NAME,STUDY_STATUS,STATUS_DESC_THAI,STILL_STUDENT,NATIONALITY,SEX_SHORT_NAME_THAI,SEX_NAME_THAI,ENT_METHOD,ENT_METHOD_DESC,STUD_BIRTH_DATE,STUD_BIRTH_PROVINCE_ID,PROVINCE_NAME_THAI,BIRTH_COUNTRY,COUNTRY_NAME_ENG,PREV_INSTITUTION_NAME,INSTITUTION_PROVINCE_ID,INSTITUTION_PROVINCE_NAME,ENG_SCORE,CAMPUS_ID,CAMPUS_NAME_THAI,IS_GRAD_IN_COURSE,CURR_REG,IN_PROVINCE,IN_PROVINCE_CAMPUS,เกรดปี1เทอม1,เกรดปี1เทอม2,เกรดปี1เทอม3,เกรดปี2เทอม1,เกรดปี2เทอม2,เกรดปี2เทอม3,เกรดปี3เทอม1,เกรดปี3เทอม2,เกรดปี3เทอม3,เกรดปี4เทอม1,เกรดปี4เทอม2,เกรดปี4เทอม3,GPA_SCHOOL,FUND_NAME,FUND_NAME_CODE,DEFORMITY_NAME_code,PARENTS_MARRIED_NAME,PARENTS_MARRIED_NAME_CODE
0,Y6rAL6a3ug,2559.0,1.0,215.0,วิศวกรรมเครื่องกล,30.0,ภาควิชาวิศวกรรมเครื่องกล,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,218.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมเครื่องกล),หลักสูตรปกติ,G,สำเร็จการศึกษา (พ้นสภาพการเป็นนักศึกษา),N,T,ช,ชาย,77,โครงการคัดเลือกบุคคลเข้าศึกษาโดยใช้ผลคะแนนสอบ ...,1997-11-16,53.0,ตรัง,TH,THAILAND,โรงเรียนหาดใหญ่วิทยาลัยสมบูรณ์กุลกันยา,62,สงขลา,41.00,1.0,วิทยาเขตหาดใหญ่,Y,FT,N,Y,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,3.10,ไม่ได้รับทุน,N,N,อยู่ด้วยกัน,9.0
1,ihEYqG7Q2P,2559.0,1.0,225.0,วิศวกรรมอุตสาหการ,31.0,ภาควิชาวิศวกรรมอุตสาหการ,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,228.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมอุตสาหการ),หลักสูตรปกติ,E,ลาออก (พ้นสภาพการเป็นนักศึกษา),N,T,ญ,หญิง,01,โครงการคัดเลือกนักเรียนใน 14 จังหวัดภาคใต้ เข...,1998-01-12,61.0,ระนอง,TH,THAILAND,โรงเรียนศรียาภัย,52,ชุมพร,52.00,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,2.97,2.30,2.50,2.97,3.36,2.75,3.60,3.9,0.00,3.83,4.00,0.0,3.32,ไม่ได้รับทุน,N,N,อยู่ด้วยกัน,9.0
2,EJwFAHDeDB,2559.0,1.0,210.0,วิศวกรรมไฟฟ้า,28.0,ภาควิชาวิศวกรรมไฟฟ้า,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,213.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมไฟฟ้า),หลักสูตรปกติ,G,สำเร็จการศึกษา (พ้นสภาพการเป็นนักศึกษา),N,T,ญ,หญิง,40,"โครงการ ""ทุนมงคลสุข""",1997-02-24,62.0,สงขลา,TH,THAILAND,โรงเรียนจะนะชนูปถัมภ์,62,สงขลา,28.00,1.0,วิทยาเขตหาดใหญ่,Y,FT,Y,Y,1.73,1.05,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,3.78,ได้รับทุน,Y,N,บิดาและมารดาแต่งงานใหม่,4.0
3,mAN7tIZz44,2559.0,1.0,215.0,วิศวกรรมเครื่องกล,30.0,ภาควิชาวิศวกรรมเครื่องกล,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,218.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมเครื่องกล),หลักสูตรปกติ,R,ตกออก (พ้นสภาพการเป็นนักศึกษา),N,T,ช,ชาย,01,โครงการคัดเลือกนักเรียนใน 14 จังหวัดภาคใต้ เข...,1997-09-01,60.0,ยะลา,TH,THAILAND,โรงเรียนราชมุนีรังสฤษฏ์,56,ปัตตานี,21.00,1.0,วิทยาเขตหาดใหญ่,Y,FT,N,N,2.50,2.94,3.25,3.47,3.27,3.23,3.47,0.0,3.31,3.73,0.00,0.0,3.77,ได้รับทุน,Y,N,บิดาถึงแก่กรรม,6.0
4,rWseDSww8R,2559.0,1.0,235.0,วิศวกรรมเหมืองแร่,33.0,ภาควิชาวิศวกรรมเหมืองแร่และวัสดุ,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,240.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมเหมืองแร่),หลักสูตรปกติ,G,สำเร็จการศึกษา (พ้นสภาพการเป็นนักศึกษา),N,T,ช,ชาย,38,โครงการรับนักเรียนที่มีผลการเรียนดี,1997-10-05,63.0,สตูล,TH,THAILAND,โรงเรียนจุฬาภรณราชวิทยาลัย สตูล,63,สตูล,21.00,1.0,วิทยาเขตหาดใหญ่,Y,FT,N,N,1.93,2.08,1.86,1.78,0.00,2.08,1.41,0.0,0.87,1.22,0.72,0.0,3.21,ไม่ได้รับทุน,N,N,อยู่ด้วยกัน,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4115,mPcmlJsEow,2564.0,1.0,210.0,วิศวกรรมไฟฟ้า,28.0,ภาควิชาวิศวกรรมไฟฟ้า,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,213.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมไฟฟ้า),หลักสูตรปกติ,OK,กำลังศึกษา,Y,T,ช,ชาย,39,"โครงการ ""โควตาวิศวกรรมศาสตร์ มอ.""",2000-01-26,60.0,ยะลา,TH,THAILAND,โรงเรียนธรรมวิทยามูลนิธิ,60,ยะลา,22.50,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,2.70,2.48,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,3.54,NaN,other,N,อยู่ด้วยกัน,9.0
4116,IY8jWx00mt,2564.0,1.0,226.0,วิศวกรรมการผลิต,31.0,ภาควิชาวิศวกรรมอุตสาหการ,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,239.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมการผลิต),หลักสูตรปกติ,OK,กำลังศึกษา,Y,T,ช,ชาย,39,"โครงการ ""โควตาวิศวกรรมศาสตร์ มอ.""",2002-08-25,63.0,สตูล,TH,THAILAND,โรงเรียนควนโดนวิทยา,63,สตูล,37.50,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,3.27,3.27,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,3.74,NaN,other,N,อยู่ด้วยกัน,9.0
4117,uVfxDYkac8,2564.0,1.0,203.0,วิศวกรรมและการจัดการนวัตกรรม,193.0,คณะวิศวกรรมศาสตร์,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,4.0,ภาคปกติ (นานาชาติ),แผนการศึกษา ป.ตรี,254.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมและการจัดการนวัตก...,หลักสูตรนานาชาติ,OK,กำลังศึกษา,Y,T,ญ,หญิง,P4,โครงการคัดเลือกนักเรียนเข้าศึกษาในคณะวิศวกรรมศ...,2003-02-25,62.0,สงขลา,TH,THAILAND,โรงเรียนธิดานุเคราะห์,62,สงขลา,61.25,1.0,วิทยาเขตหาดใหญ่,N,FT,Y,Y,2.56,3.15,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,3.25,NaN,other,N,อยู่ด้วยกัน,9.0
4118,IcXALKhfPP,2564.0,1.0,203.0,วิศวกรรมและการจัดการนวัตกรรม,193.0,คณะวิศวกรรมศาสตร์,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,4.0,ภาคปกติ (นานาชาติ),แผนการศึกษา ป.ตรี,254.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมและการจัดการนวัตก...,หลักสูตรนานาชาติ,OK,กำลังศึกษา,Y,T,ช,ชาย,P4,โครงการคัดเลือกนักเรียนเข้าศึกษาในคณะวิศวกรรมศ...,1998-04-01,63.0,สตูล,TH,THAILAND,โรงเรียนดารุลมาอาเรฟมูลนิธิ,63,สตูล,21.25,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,3.64,3.50,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,2.79,NaN,other,N,มารดาถึงแก่กรรม,8.0
4119,q5SWpcypnh,2564.0,1.0,203.0,วิศวกรรมและการจัดการนวัตกรรม,193.0,คณะวิศวกรรมศาสตร์,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,4.0,ภาคปกติ (นานาชาติ),แผนการศึกษา ป.ตรี,254.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมและการจัดการนวัตก...,หลักสูตรนานาชาติ,OK,กำลังศึกษา,Y,T,ช,ชาย,P4,โครงการคัดเลือกนักเรียนเข้าศึกษาในคณะวิศวกรรมศ...,2003-01-30,54.0,นครศรีธรรมราช,TH,THAILAND,โรงเรียนปากพะยูนพิทยาคาร,58,พัทลุง,56.25,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,3.17,2.78,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,3.26,ไม่ได้รับทุน,N,N,อยู่ด้วยกัน,9.0

In [61]:
raw_datas.to_csv("../data/data_dropout_59-64(1).csv",index=False)

In [62]:
for i in raw_datas[(raw_datas['ADMIT_YEAR'] == 2561) & ((raw_datas['STUDY_STATUS'] != 'R'))]['เกรดปี4เทอม2']:
    print(i)

0.0
0.0
0.0
0.0
2.76
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3.93
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3.38
0.0
0.0
0.0
0.0
0.0
2.92
0.0
0.0
0.0
3.43
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
3.5
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3.86
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3.35
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
4.0
2.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
3.45
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3.5
3.5
3.5
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
4.0
0.0
0.0
0.0
3.5
3.05
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2.32
0.0
3.8
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3.24
4.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3.75
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
1.53
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
4.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3.88
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3.8
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
4.0
4.0
2.95
0.0
4.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2.5
0.0
3.81
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3.52
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3.83
0.0
3.37
0.0
3.75
0.0
0.0
0.0
0.0
0.0
0.0
4.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3.12
0.0
0.0
2.92
0.0
0.0
3.26
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3.03
0.0
0.0
0.0
0.0
2.0
0.0
0.0
0.0
0.0
1.5
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2.23
0.0
0.0
2.2
0.0
3.63
1.71
3.75
0.0
0.0
0.0
0.0
3.0
0.0
0.0
0.0
0.0
0.0
0.0
2.5
0.0
3.7
0.0
1.61
0.0
0.0
0.0
3.5
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3.22
0.0
0.0
0.0
0.0
0.0
0.0
3.0
0.0
0.0
3.2
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
2.78
0.0
0.0
0.0
1.58
1.6
0.0
0.0
3.25
4.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
4.0
0.0
0.0
0.0
0.0
0.0
0.0
1.5
0.77
0.0
0.0
0.0
0.0
3.5
0.0
0.0
0.0
0.0
0.0
0.0

In [63]:
raw_datas = raw_datas.drop(raw_datas[(raw_datas['ADMIT_YEAR'] == 2561) & ((raw_datas['STUDY_STATUS'] != 'R') & (raw_datas['STUDY_STATUS'] != 'E')) & (raw_datas['เกรดปี4เทอม1'] == 0)].index)

In [64]:
raw_datas

,STUDENT_ID,ADMIT_YEAR,ADMIT_TERM,MAJOR_ID,MAJOR_NAME_THAI,DEPT_ID,DEPT_NAME_THAI,FAC_ID,FAC_NAME_THAI,STUDY_LEVEL_ID,STUDY_LEVEL_NAME,STUDY_TYPE_ID,STUDY_TYPE_NAME,STUDY_PLAN_NAME,DEGREE_ID,COURSE_NAME,COURSE_DEGREE,COURSE_TYPE_NAME,STUDY_STATUS,STATUS_DESC_THAI,STILL_STUDENT,NATIONALITY,SEX_SHORT_NAME_THAI,SEX_NAME_THAI,ENT_METHOD,ENT_METHOD_DESC,STUD_BIRTH_DATE,STUD_BIRTH_PROVINCE_ID,PROVINCE_NAME_THAI,BIRTH_COUNTRY,COUNTRY_NAME_ENG,PREV_INSTITUTION_NAME,INSTITUTION_PROVINCE_ID,INSTITUTION_PROVINCE_NAME,ENG_SCORE,CAMPUS_ID,CAMPUS_NAME_THAI,IS_GRAD_IN_COURSE,CURR_REG,IN_PROVINCE,IN_PROVINCE_CAMPUS,เกรดปี1เทอม1,เกรดปี1เทอม2,เกรดปี1เทอม3,เกรดปี2เทอม1,เกรดปี2เทอม2,เกรดปี2เทอม3,เกรดปี3เทอม1,เกรดปี3เทอม2,เกรดปี3เทอม3,เกรดปี4เทอม1,เกรดปี4เทอม2,เกรดปี4เทอม3,GPA_SCHOOL,FUND_NAME,FUND_NAME_CODE,DEFORMITY_NAME_code,PARENTS_MARRIED_NAME,PARENTS_MARRIED_NAME_CODE
0,Y6rAL6a3ug,2559.0,1.0,215.0,วิศวกรรมเครื่องกล,30.0,ภาควิชาวิศวกรรมเครื่องกล,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,218.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมเครื่องกล),หลักสูตรปกติ,G,สำเร็จการศึกษา (พ้นสภาพการเป็นนักศึกษา),N,T,ช,ชาย,77,โครงการคัดเลือกบุคคลเข้าศึกษาโดยใช้ผลคะแนนสอบ ...,1997-11-16,53.0,ตรัง,TH,THAILAND,โรงเรียนหาดใหญ่วิทยาลัยสมบูรณ์กุลกันยา,62,สงขลา,41.00,1.0,วิทยาเขตหาดใหญ่,Y,FT,N,Y,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,3.10,ไม่ได้รับทุน,N,N,อยู่ด้วยกัน,9.0
1,ihEYqG7Q2P,2559.0,1.0,225.0,วิศวกรรมอุตสาหการ,31.0,ภาควิชาวิศวกรรมอุตสาหการ,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,228.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมอุตสาหการ),หลักสูตรปกติ,E,ลาออก (พ้นสภาพการเป็นนักศึกษา),N,T,ญ,หญิง,01,โครงการคัดเลือกนักเรียนใน 14 จังหวัดภาคใต้ เข...,1998-01-12,61.0,ระนอง,TH,THAILAND,โรงเรียนศรียาภัย,52,ชุมพร,52.00,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,2.97,2.30,2.50,2.97,3.36,2.75,3.60,3.9,0.00,3.83,4.00,0.0,3.32,ไม่ได้รับทุน,N,N,อยู่ด้วยกัน,9.0
2,EJwFAHDeDB,2559.0,1.0,210.0,วิศวกรรมไฟฟ้า,28.0,ภาควิชาวิศวกรรมไฟฟ้า,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,213.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมไฟฟ้า),หลักสูตรปกติ,G,สำเร็จการศึกษา (พ้นสภาพการเป็นนักศึกษา),N,T,ญ,หญิง,40,"โครงการ ""ทุนมงคลสุข""",1997-02-24,62.0,สงขลา,TH,THAILAND,โรงเรียนจะนะชนูปถัมภ์,62,สงขลา,28.00,1.0,วิทยาเขตหาดใหญ่,Y,FT,Y,Y,1.73,1.05,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,3.78,ได้รับทุน,Y,N,บิดาและมารดาแต่งงานใหม่,4.0
3,mAN7tIZz44,2559.0,1.0,215.0,วิศวกรรมเครื่องกล,30.0,ภาควิชาวิศวกรรมเครื่องกล,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,218.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมเครื่องกล),หลักสูตรปกติ,R,ตกออก (พ้นสภาพการเป็นนักศึกษา),N,T,ช,ชาย,01,โครงการคัดเลือกนักเรียนใน 14 จังหวัดภาคใต้ เข...,1997-09-01,60.0,ยะลา,TH,THAILAND,โรงเรียนราชมุนีรังสฤษฏ์,56,ปัตตานี,21.00,1.0,วิทยาเขตหาดใหญ่,Y,FT,N,N,2.50,2.94,3.25,3.47,3.27,3.23,3.47,0.0,3.31,3.73,0.00,0.0,3.77,ได้รับทุน,Y,N,บิดาถึงแก่กรรม,6.0
4,rWseDSww8R,2559.0,1.0,235.0,วิศวกรรมเหมืองแร่,33.0,ภาควิชาวิศวกรรมเหมืองแร่และวัสดุ,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,240.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมเหมืองแร่),หลักสูตรปกติ,G,สำเร็จการศึกษา (พ้นสภาพการเป็นนักศึกษา),N,T,ช,ชาย,38,โครงการรับนักเรียนที่มีผลการเรียนดี,1997-10-05,63.0,สตูล,TH,THAILAND,โรงเรียนจุฬาภรณราชวิทยาลัย สตูล,63,สตูล,21.00,1.0,วิทยาเขตหาดใหญ่,Y,FT,N,N,1.93,2.08,1.86,1.78,0.00,2.08,1.41,0.0,0.87,1.22,0.72,0.0,3.21,ไม่ได้รับทุน,N,N,อยู่ด้วยกัน,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4115,mPcmlJsEow,2564.0,1.0,210.0,วิศวกรรมไฟฟ้า,28.0,ภาควิชาวิศวกรรมไฟฟ้า,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,213.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมไฟฟ้า),หลักสูตรปกติ,OK,กำลังศึกษา,Y,T,ช,ชาย,39,"โครงการ ""โควตาวิศวกรรมศาสตร์ มอ.""",2000-01-26,60.0,ยะลา,TH,THAILAND,โรงเรียนธรรมวิทยามูลนิธิ,60,ยะลา,22.50,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,2.70,2.48,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,3.54,NaN,other,N,อยู่ด้วยกัน,9.0
4116,IY8jWx00mt,2564.0,1.0,226.0,วิศวกรรมการผลิต,31.0,ภาควิชาวิศวกรรมอุตสาหการ,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,239.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมการผลิต),หลักสูตรปกติ,OK,กำลังศึกษา,Y,T,ช,ชาย,39,"โครงการ ""โควตาวิศวกรรมศาสตร์ มอ.""",2002-08-25,63.0,สตูล,TH,THAILAND,โรงเรียนควนโดนวิทยา,63,สตูล,37.50,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,3.27,3.27,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,3.74,NaN,other,N,อยู่ด้วยกัน,9.0
4117,uVfxDYkac8,2564.0,1.0,203.0,วิศวกรรมและการจัดการนวัตกรรม,193.0,คณะวิศวกรรมศาสตร์,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,4.0,ภาคปกติ (นานาชาติ),แผนการศึกษา ป.ตรี,254.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมและการจัดการนวัตก...,หลักสูตรนานาชาติ,OK,กำลังศึกษา,Y,T,ญ,หญิง,P4,โครงการคัดเลือกนักเรียนเข้าศึกษาในคณะวิศวกรรมศ...,2003-02-25,62.0,สงขลา,TH,THAILAND,โรงเรียนธิดานุเคราะห์,62,สงขลา,61.25,1.0,วิทยาเขตหาดใหญ่,N,FT,Y,Y,2.56,3.15,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,3.25,NaN,other,N,อยู่ด้วยกัน,9.0
4118,IcXALKhfPP,2564.0,1.0,203.0,วิศวกรรมและการจัดการนวัตกรรม,193.0,คณะวิศวกรรมศาสตร์,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,4.0,ภาคปกติ (นานาชาติ),แผนการศึกษา ป.ตรี,254.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมและการจัดการนวัตก...,หลักสูตรนานาชาติ,OK,กำลังศึกษา,Y,T,ช,ชาย,P4,โครงการคัดเลือกนักเรียนเข้าศึกษาในคณะวิศวกรรมศ...,1998-04-01,63.0,สตูล,TH,THAILAND,โรงเรียนดารุลมาอาเรฟมูลนิธิ,63,สตูล,21.25,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,3.64,3.50,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,2.79,NaN,other,N,มารดาถึงแก่กรรม,8.0
4119,q5SWpcypnh,2564.0,1.0,203.0,วิศวกรรมและการจัดการนวัตกรรม,193.0,คณะวิศวกรรมศาสตร์,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,4.0,ภาคปกติ (นานาชาติ),แผนการศึกษา ป.ตรี,254.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมและการจัดการนวัตก...,หลักสูตรนานาชาติ,OK,กำลังศึกษา,Y,T,ช,ชาย,P4,โครงการคัดเลือกนักเรียนเข้าศึกษาในคณะวิศวกรรมศ...,2003-01-30,54.0,นครศรีธรรมราช,TH,THAILAND,โรงเรียนปากพะยูนพิทยาคาร,58,พัทลุง,56.25,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,3.17,2.78,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,3.26,ไม่ได้รับทุน,N,N,อยู่ด้วยกัน,9.0

In [65]:
raw_datas[(raw_datas['ADMIT_YEAR'] == 2563) & ((raw_datas['STUDY_STATUS'] != 'R') & (raw_datas['STUDY_STATUS'] != 'E')) & (raw_datas['เกรดปี2เทอม2'] != 0)]

,STUDENT_ID,ADMIT_YEAR,ADMIT_TERM,MAJOR_ID,MAJOR_NAME_THAI,DEPT_ID,DEPT_NAME_THAI,FAC_ID,FAC_NAME_THAI,STUDY_LEVEL_ID,STUDY_LEVEL_NAME,STUDY_TYPE_ID,STUDY_TYPE_NAME,STUDY_PLAN_NAME,DEGREE_ID,COURSE_NAME,COURSE_DEGREE,COURSE_TYPE_NAME,STUDY_STATUS,STATUS_DESC_THAI,STILL_STUDENT,NATIONALITY,SEX_SHORT_NAME_THAI,SEX_NAME_THAI,ENT_METHOD,ENT_METHOD_DESC,STUD_BIRTH_DATE,STUD_BIRTH_PROVINCE_ID,PROVINCE_NAME_THAI,BIRTH_COUNTRY,COUNTRY_NAME_ENG,PREV_INSTITUTION_NAME,INSTITUTION_PROVINCE_ID,INSTITUTION_PROVINCE_NAME,ENG_SCORE,CAMPUS_ID,CAMPUS_NAME_THAI,IS_GRAD_IN_COURSE,CURR_REG,IN_PROVINCE,IN_PROVINCE_CAMPUS,เกรดปี1เทอม1,เกรดปี1เทอม2,เกรดปี1เทอม3,เกรดปี2เทอม1,เกรดปี2เทอม2,เกรดปี2เทอม3,เกรดปี3เทอม1,เกรดปี3เทอม2,เกรดปี3เทอม3,เกรดปี4เทอม1,เกรดปี4เทอม2,เกรดปี4เทอม3,GPA_SCHOOL,FUND_NAME,FUND_NAME_CODE,DEFORMITY_NAME_code,PARENTS_MARRIED_NAME,PARENTS_MARRIED_NAME_CODE
2716,hk0la7Qu19,2563.0,1.0,220.0,วิศวกรรมโยธา,29.0,ภาควิชาวิศวกรรมโยธา,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,223.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมโยธา),หลักสูตรปกติ,OK,กำลังศึกษา,Y,T,ญ,หญิง,38,โครงการรับนักเรียนที่มีผลการเรียนดี,2001-07-16,53.0,ตรัง,TH,THAILAND,โรงเรียนห้วยยอด,53,ตรัง,43.75,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,3.44,3.40,2.59,2.76,1.50,2.87,2.63,0.0,0.0,0.0,0.0,0.0,3.34,ไม่ได้รับทุน,N,N,อยู่ด้วยกัน,9.0
2727,MnfncCbAjs,2563.0,1.0,226.0,วิศวกรรมการผลิต,31.0,ภาควิชาวิศวกรรมอุตสาหการ,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,239.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมการผลิต),หลักสูตรปกติ,OK,กำลังศึกษา,Y,T,ญ,หญิง,38,โครงการรับนักเรียนที่มีผลการเรียนดี,2001-02-28,62.0,สงขลา,TH,THAILAND,โรงเรียนอำมาตย์พานิชนุกูล,51,กระบี่,45.00,1.0,วิทยาเขตหาดใหญ่,N,FT,Y,N,3.02,2.92,4.00,3.34,3.50,0.00,0.00,0.0,0.0,0.0,0.0,0.0,2.93,ไม่ได้รับทุน,N,N,อยู่ด้วยกัน,9.0
2728,hlMtq42fi5,2563.0,1.0,240.0,วิศวกรรมคอมพิวเตอร์,34.0,ภาควิชาวิศวกรรมคอมพิวเตอร์,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,243.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมคอมพิวเตอร์),หลักสูตรปกติ,OK,กำลังศึกษา,Y,T,ช,ชาย,36,Admission,2002-05-21,60.0,ยะลา,TH,THAILAND,โรงเรียนระโนด จังหวัดสงขลา,62,สงขลา,33.75,1.0,วิทยาเขตหาดใหญ่,N,FT,N,Y,2.12,2.09,3.00,1.85,2.18,4.00,0.00,0.0,0.0,0.0,0.0,0.0,2.68,ไม่ได้รับทุน,N,N,บิดาถึงแก่กรรม,6.0
2733,2zepDvf8ar,2563.0,1.0,216.0,วิศวกรรมเมคาทรอนิกส์,30.0,ภาควิชาวิศวกรรมเครื่องกล,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,242.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมเมคาทรอนิกส์),หลักสูตรปกติ,OK,กำลังศึกษา,Y,T,ช,ชาย,36,Admission,2002-01-31,62.0,สงขลา,TH,THAILAND,โรงเรียนส่งเสริมศาสนาวิทยามูลนิธิ,62,สงขลา,25.00,1.0,วิทยาเขตหาดใหญ่,N,FT,Y,Y,2.72,2.80,4.00,2.82,3.20,0.00,0.00,0.0,0.0,0.0,0.0,0.0,2.83,ไม่ได้รับทุน,N,N,อยู่ด้วยกัน,9.0
2735,Ec0UZRazPB,2563.0,1.0,230.0,วิศวกรรมเคมี,32.0,ภาควิชาวิศวกรรมเคมี,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,233.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมเคมี),หลักสูตรปกติ,OK,กำลังศึกษา,Y,T,ช,ชาย,38,โครงการรับนักเรียนที่มีผลการเรียนดี,2001-09-02,60.0,ยะลา,TH,THAILAND,โรงเรียนคณะราษฎรบำรุง จังหวัดยะลา,60,ยะลา,71.25,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,2.35,2.19,2.57,3.15,2.50,0.00,0.00,0.0,0.0,0.0,0.0,0.0,3.43,ไม่ได้รับทุน,N,N,อยู่ด้วยกัน,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3369,YvbggsVwjr,2563.0,1.0,225.0,วิศวกรรมอุตสาหการ,31.0,ภาควิชาวิศวกรรมอุตสาหการ,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,228.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมอุตสาหการ),หลักสูตรปกติ,OK,กำลังศึกษา,Y,T,ช,ชาย,36,Admission,2000-07-28,46.0,ตราด,TH,THAILAND,โรงเรียนคลองใหญ่วิทยาคม,46,ตราด,38.75,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,3.83,2.56,2.55,2.85,3.16,0.00,0.00,0.0,0.0,0.0,0.0,0.0,3.74,ไม่ได้รับทุน,N,N,แยกกันอยู่เพราะสาเหตุอื่น,2.0
3370,Q2lPbtoyNv,2563.0,1.0,210.0,วิศวกรรมไฟฟ้า,28.0,ภาควิชาวิศวกรรมไฟฟ้า,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,213.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมไฟฟ้า),หลักสูตรปกติ,OK,กำลังศึกษา,Y,T,ญ,หญิง,36,Admission,2000-04-05,55.0,นราธิวาส,TH,THAILAND,โรงเรียนดารุสสาลาม,55,นราธิวาส,55.00,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,3.07,2.65,3.88,2.62,2.52,0.00,0.00,0.0,0.0,0.0,0.0,0.0,3.91,ไม่ได้รับทุน,N,N,บิดาถึงแก่กรรม,6.0
3373,xHBJMElCv1,2563.0,1.0,214.0,วิศวกรรมชีวการแพทย์,28.0,ภาควิชาวิศวกรรมไฟฟ้า,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,211.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมชีวการแพทย์),หลักสูตรปกติ,OK,กำลังศึกษา,Y,T,ญ,หญิง,36,Admission,1999-03-27,62.0,สงขลา,TH,THAILAND,โรงเรียนหาดใหญ่วิทยาลัย,62,สงขลา,27.50,1.0,วิทยาเขตหาดใหญ่,N,FT,Y,Y,2.19,1.66,2.03,2.81,4.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,3.06,ไม่ได้รับทุน,N,N,อยู่ด้วยกัน,9.0
3387,BxaYJI986b,2563.0,1.0,205.0,วิศวกรรมสิ่งแวดล้อม,29.0,ภาควิชาวิศวกรรมโยธา,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,245.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมสิ่งแวดล้อม),หลักสูตรปกติ,OK,กำลังศึกษา,Y,T,ญ,หญิง,39,"โครงการ ""โควตาวิศวกรรมศาสตร์ มอ.""",2001-11-23,60.0,ยะลา,TH,THAILAND,โรงเรียนคณะราษฎรบำรุง จังหวัดยะลา,60,ยะลา,37.50,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,3.32,1.00,0.93,2.00,2.51,1.91,0.00,0.0,0.0,0.0,0.0,0.0,3.51,ไม่ได้รับทุน,N,N,อยู่ด้วยกัน,9.0
3390,P1cK8Kk41T,2563.0,1.0,226.0,วิศวกรรมการผลิต,31.0,ภาควิชาวิศวกรรมอุตสาหการ,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,239.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมการผลิต),หลักสูตรปกติ,OK,กำลังศึกษา,Y,T,ญ,หญิง,39,"โครงการ ""โควตาวิศวกรรมศาสตร์ มอ.""",2001-03-29,53.0,ตรัง,TH,THAILAND,โรงเรียนวังวิเศษ,53,ตรัง,27.50,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,2.13,1.91,0.00,2.08,2.93,2.00,0.00,0.0,0.0,0.0,0.0,0.0,3.05,ไม่ได้รับทุน,N,N,แยกกันอยู่เพราะสาเหตุอื่น,2.0

In [66]:
raw_datas = raw_datas.drop(['SEX_SHORT_NAME_THAI'],axis=1)

In [67]:
raw_datas

,STUDENT_ID,ADMIT_YEAR,ADMIT_TERM,MAJOR_ID,MAJOR_NAME_THAI,DEPT_ID,DEPT_NAME_THAI,FAC_ID,FAC_NAME_THAI,STUDY_LEVEL_ID,STUDY_LEVEL_NAME,STUDY_TYPE_ID,STUDY_TYPE_NAME,STUDY_PLAN_NAME,DEGREE_ID,COURSE_NAME,COURSE_DEGREE,COURSE_TYPE_NAME,STUDY_STATUS,STATUS_DESC_THAI,STILL_STUDENT,NATIONALITY,SEX_NAME_THAI,ENT_METHOD,ENT_METHOD_DESC,STUD_BIRTH_DATE,STUD_BIRTH_PROVINCE_ID,PROVINCE_NAME_THAI,BIRTH_COUNTRY,COUNTRY_NAME_ENG,PREV_INSTITUTION_NAME,INSTITUTION_PROVINCE_ID,INSTITUTION_PROVINCE_NAME,ENG_SCORE,CAMPUS_ID,CAMPUS_NAME_THAI,IS_GRAD_IN_COURSE,CURR_REG,IN_PROVINCE,IN_PROVINCE_CAMPUS,เกรดปี1เทอม1,เกรดปี1เทอม2,เกรดปี1เทอม3,เกรดปี2เทอม1,เกรดปี2เทอม2,เกรดปี2เทอม3,เกรดปี3เทอม1,เกรดปี3เทอม2,เกรดปี3เทอม3,เกรดปี4เทอม1,เกรดปี4เทอม2,เกรดปี4เทอม3,GPA_SCHOOL,FUND_NAME,FUND_NAME_CODE,DEFORMITY_NAME_code,PARENTS_MARRIED_NAME,PARENTS_MARRIED_NAME_CODE
0,Y6rAL6a3ug,2559.0,1.0,215.0,วิศวกรรมเครื่องกล,30.0,ภาควิชาวิศวกรรมเครื่องกล,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,218.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมเครื่องกล),หลักสูตรปกติ,G,สำเร็จการศึกษา (พ้นสภาพการเป็นนักศึกษา),N,T,ชาย,77,โครงการคัดเลือกบุคคลเข้าศึกษาโดยใช้ผลคะแนนสอบ ...,1997-11-16,53.0,ตรัง,TH,THAILAND,โรงเรียนหาดใหญ่วิทยาลัยสมบูรณ์กุลกันยา,62,สงขลา,41.00,1.0,วิทยาเขตหาดใหญ่,Y,FT,N,Y,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,3.10,ไม่ได้รับทุน,N,N,อยู่ด้วยกัน,9.0
1,ihEYqG7Q2P,2559.0,1.0,225.0,วิศวกรรมอุตสาหการ,31.0,ภาควิชาวิศวกรรมอุตสาหการ,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,228.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมอุตสาหการ),หลักสูตรปกติ,E,ลาออก (พ้นสภาพการเป็นนักศึกษา),N,T,หญิง,01,โครงการคัดเลือกนักเรียนใน 14 จังหวัดภาคใต้ เข...,1998-01-12,61.0,ระนอง,TH,THAILAND,โรงเรียนศรียาภัย,52,ชุมพร,52.00,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,2.97,2.30,2.50,2.97,3.36,2.75,3.60,3.9,0.00,3.83,4.00,0.0,3.32,ไม่ได้รับทุน,N,N,อยู่ด้วยกัน,9.0
2,EJwFAHDeDB,2559.0,1.0,210.0,วิศวกรรมไฟฟ้า,28.0,ภาควิชาวิศวกรรมไฟฟ้า,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,213.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมไฟฟ้า),หลักสูตรปกติ,G,สำเร็จการศึกษา (พ้นสภาพการเป็นนักศึกษา),N,T,หญิง,40,"โครงการ ""ทุนมงคลสุข""",1997-02-24,62.0,สงขลา,TH,THAILAND,โรงเรียนจะนะชนูปถัมภ์,62,สงขลา,28.00,1.0,วิทยาเขตหาดใหญ่,Y,FT,Y,Y,1.73,1.05,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,3.78,ได้รับทุน,Y,N,บิดาและมารดาแต่งงานใหม่,4.0
3,mAN7tIZz44,2559.0,1.0,215.0,วิศวกรรมเครื่องกล,30.0,ภาควิชาวิศวกรรมเครื่องกล,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,218.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมเครื่องกล),หลักสูตรปกติ,R,ตกออก (พ้นสภาพการเป็นนักศึกษา),N,T,ชาย,01,โครงการคัดเลือกนักเรียนใน 14 จังหวัดภาคใต้ เข...,1997-09-01,60.0,ยะลา,TH,THAILAND,โรงเรียนราชมุนีรังสฤษฏ์,56,ปัตตานี,21.00,1.0,วิทยาเขตหาดใหญ่,Y,FT,N,N,2.50,2.94,3.25,3.47,3.27,3.23,3.47,0.0,3.31,3.73,0.00,0.0,3.77,ได้รับทุน,Y,N,บิดาถึงแก่กรรม,6.0
4,rWseDSww8R,2559.0,1.0,235.0,วิศวกรรมเหมืองแร่,33.0,ภาควิชาวิศวกรรมเหมืองแร่และวัสดุ,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,240.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมเหมืองแร่),หลักสูตรปกติ,G,สำเร็จการศึกษา (พ้นสภาพการเป็นนักศึกษา),N,T,ชาย,38,โครงการรับนักเรียนที่มีผลการเรียนดี,1997-10-05,63.0,สตูล,TH,THAILAND,โรงเรียนจุฬาภรณราชวิทยาลัย สตูล,63,สตูล,21.00,1.0,วิทยาเขตหาดใหญ่,Y,FT,N,N,1.93,2.08,1.86,1.78,0.00,2.08,1.41,0.0,0.87,1.22,0.72,0.0,3.21,ไม่ได้รับทุน,N,N,อยู่ด้วยกัน,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4115,mPcmlJsEow,2564.0,1.0,210.0,วิศวกรรมไฟฟ้า,28.0,ภาควิชาวิศวกรรมไฟฟ้า,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,213.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมไฟฟ้า),หลักสูตรปกติ,OK,กำลังศึกษา,Y,T,ชาย,39,"โครงการ ""โควตาวิศวกรรมศาสตร์ มอ.""",2000-01-26,60.0,ยะลา,TH,THAILAND,โรงเรียนธรรมวิทยามูลนิธิ,60,ยะลา,22.50,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,2.70,2.48,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,3.54,NaN,other,N,อยู่ด้วยกัน,9.0
4116,IY8jWx00mt,2564.0,1.0,226.0,วิศวกรรมการผลิต,31.0,ภาควิชาวิศวกรรมอุตสาหการ,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,239.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมการผลิต),หลักสูตรปกติ,OK,กำลังศึกษา,Y,T,ชาย,39,"โครงการ ""โควตาวิศวกรรมศาสตร์ มอ.""",2002-08-25,63.0,สตูล,TH,THAILAND,โรงเรียนควนโดนวิทยา,63,สตูล,37.50,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,3.27,3.27,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,3.74,NaN,other,N,อยู่ด้วยกัน,9.0
4117,uVfxDYkac8,2564.0,1.0,203.0,วิศวกรรมและการจัดการนวัตกรรม,193.0,คณะวิศวกรรมศาสตร์,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,4.0,ภาคปกติ (นานาชาติ),แผนการศึกษา ป.ตรี,254.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมและการจัดการนวัตก...,หลักสูตรนานาชาติ,OK,กำลังศึกษา,Y,T,หญิง,P4,โครงการคัดเลือกนักเรียนเข้าศึกษาในคณะวิศวกรรมศ...,2003-02-25,62.0,สงขลา,TH,THAILAND,โรงเรียนธิดานุเคราะห์,62,สงขลา,61.25,1.0,วิทยาเขตหาดใหญ่,N,FT,Y,Y,2.56,3.15,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,3.25,NaN,other,N,อยู่ด้วยกัน,9.0
4118,IcXALKhfPP,2564.0,1.0,203.0,วิศวกรรมและการจัดการนวัตกรรม,193.0,คณะวิศวกรรมศาสตร์,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,4.0,ภาคปกติ (นานาชาติ),แผนการศึกษา ป.ตรี,254.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมและการจัดการนวัตก...,หลักสูตรนานาชาติ,OK,กำลังศึกษา,Y,T,ชาย,P4,โครงการคัดเลือกนักเรียนเข้าศึกษาในคณะวิศวกรรมศ...,1998-04-01,63.0,สตูล,TH,THAILAND,โรงเรียนดารุลมาอาเรฟมูลนิธิ,63,สตูล,21.25,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,3.64,3.50,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,2.79,NaN,other,N,มารดาถึงแก่กรรม,8.0
4119,q5SWpcypnh,2564.0,1.0,203.0,วิศวกรรมและการจัดการนวัตกรรม,193.0,คณะวิศวกรรมศาสตร์,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,4.0,ภาคปกติ (นานาชาติ),แผนการศึกษา ป.ตรี,254.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมและการจัดการนวัตก...,หลักสูตรนานาชาติ,OK,กำลังศึกษา,Y,T,ชาย,P4,โครงการคัดเลือกนักเรียนเข้าศึกษาในคณะวิศวกรรมศ...,2003-01-30,54.0,นครศรีธรรมราช,TH,THAILAND,โรงเรียนปากพะยูนพิทยาคาร,58,พัทลุง,56.25,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,3.17,2.78,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,3.26,ไม่ได้รับทุน,N,N,อยู่ด้วยกัน,9.0

In [68]:
raw_datas.to_csv('../data/data_dropout_59-64(4).csv',index=False)

In [69]:
raw_datas

,STUDENT_ID,ADMIT_YEAR,ADMIT_TERM,MAJOR_ID,MAJOR_NAME_THAI,DEPT_ID,DEPT_NAME_THAI,FAC_ID,FAC_NAME_THAI,STUDY_LEVEL_ID,STUDY_LEVEL_NAME,STUDY_TYPE_ID,STUDY_TYPE_NAME,STUDY_PLAN_NAME,DEGREE_ID,COURSE_NAME,COURSE_DEGREE,COURSE_TYPE_NAME,STUDY_STATUS,STATUS_DESC_THAI,STILL_STUDENT,NATIONALITY,SEX_NAME_THAI,ENT_METHOD,ENT_METHOD_DESC,STUD_BIRTH_DATE,STUD_BIRTH_PROVINCE_ID,PROVINCE_NAME_THAI,BIRTH_COUNTRY,COUNTRY_NAME_ENG,PREV_INSTITUTION_NAME,INSTITUTION_PROVINCE_ID,INSTITUTION_PROVINCE_NAME,ENG_SCORE,CAMPUS_ID,CAMPUS_NAME_THAI,IS_GRAD_IN_COURSE,CURR_REG,IN_PROVINCE,IN_PROVINCE_CAMPUS,เกรดปี1เทอม1,เกรดปี1เทอม2,เกรดปี1เทอม3,เกรดปี2เทอม1,เกรดปี2เทอม2,เกรดปี2เทอม3,เกรดปี3เทอม1,เกรดปี3เทอม2,เกรดปี3เทอม3,เกรดปี4เทอม1,เกรดปี4เทอม2,เกรดปี4เทอม3,GPA_SCHOOL,FUND_NAME,FUND_NAME_CODE,DEFORMITY_NAME_code,PARENTS_MARRIED_NAME,PARENTS_MARRIED_NAME_CODE
0,Y6rAL6a3ug,2559.0,1.0,215.0,วิศวกรรมเครื่องกล,30.0,ภาควิชาวิศวกรรมเครื่องกล,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,218.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมเครื่องกล),หลักสูตรปกติ,G,สำเร็จการศึกษา (พ้นสภาพการเป็นนักศึกษา),N,T,ชาย,77,โครงการคัดเลือกบุคคลเข้าศึกษาโดยใช้ผลคะแนนสอบ ...,1997-11-16,53.0,ตรัง,TH,THAILAND,โรงเรียนหาดใหญ่วิทยาลัยสมบูรณ์กุลกันยา,62,สงขลา,41.00,1.0,วิทยาเขตหาดใหญ่,Y,FT,N,Y,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,3.10,ไม่ได้รับทุน,N,N,อยู่ด้วยกัน,9.0
1,ihEYqG7Q2P,2559.0,1.0,225.0,วิศวกรรมอุตสาหการ,31.0,ภาควิชาวิศวกรรมอุตสาหการ,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,228.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมอุตสาหการ),หลักสูตรปกติ,E,ลาออก (พ้นสภาพการเป็นนักศึกษา),N,T,หญิง,01,โครงการคัดเลือกนักเรียนใน 14 จังหวัดภาคใต้ เข...,1998-01-12,61.0,ระนอง,TH,THAILAND,โรงเรียนศรียาภัย,52,ชุมพร,52.00,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,2.97,2.30,2.50,2.97,3.36,2.75,3.60,3.9,0.00,3.83,4.00,0.0,3.32,ไม่ได้รับทุน,N,N,อยู่ด้วยกัน,9.0
2,EJwFAHDeDB,2559.0,1.0,210.0,วิศวกรรมไฟฟ้า,28.0,ภาควิชาวิศวกรรมไฟฟ้า,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,213.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมไฟฟ้า),หลักสูตรปกติ,G,สำเร็จการศึกษา (พ้นสภาพการเป็นนักศึกษา),N,T,หญิง,40,"โครงการ ""ทุนมงคลสุข""",1997-02-24,62.0,สงขลา,TH,THAILAND,โรงเรียนจะนะชนูปถัมภ์,62,สงขลา,28.00,1.0,วิทยาเขตหาดใหญ่,Y,FT,Y,Y,1.73,1.05,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,3.78,ได้รับทุน,Y,N,บิดาและมารดาแต่งงานใหม่,4.0
3,mAN7tIZz44,2559.0,1.0,215.0,วิศวกรรมเครื่องกล,30.0,ภาควิชาวิศวกรรมเครื่องกล,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,218.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมเครื่องกล),หลักสูตรปกติ,R,ตกออก (พ้นสภาพการเป็นนักศึกษา),N,T,ชาย,01,โครงการคัดเลือกนักเรียนใน 14 จังหวัดภาคใต้ เข...,1997-09-01,60.0,ยะลา,TH,THAILAND,โรงเรียนราชมุนีรังสฤษฏ์,56,ปัตตานี,21.00,1.0,วิทยาเขตหาดใหญ่,Y,FT,N,N,2.50,2.94,3.25,3.47,3.27,3.23,3.47,0.0,3.31,3.73,0.00,0.0,3.77,ได้รับทุน,Y,N,บิดาถึงแก่กรรม,6.0
4,rWseDSww8R,2559.0,1.0,235.0,วิศวกรรมเหมืองแร่,33.0,ภาควิชาวิศวกรรมเหมืองแร่และวัสดุ,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,240.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมเหมืองแร่),หลักสูตรปกติ,G,สำเร็จการศึกษา (พ้นสภาพการเป็นนักศึกษา),N,T,ชาย,38,โครงการรับนักเรียนที่มีผลการเรียนดี,1997-10-05,63.0,สตูล,TH,THAILAND,โรงเรียนจุฬาภรณราชวิทยาลัย สตูล,63,สตูล,21.00,1.0,วิทยาเขตหาดใหญ่,Y,FT,N,N,1.93,2.08,1.86,1.78,0.00,2.08,1.41,0.0,0.87,1.22,0.72,0.0,3.21,ไม่ได้รับทุน,N,N,อยู่ด้วยกัน,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4115,mPcmlJsEow,2564.0,1.0,210.0,วิศวกรรมไฟฟ้า,28.0,ภาควิชาวิศวกรรมไฟฟ้า,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,213.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมไฟฟ้า),หลักสูตรปกติ,OK,กำลังศึกษา,Y,T,ชาย,39,"โครงการ ""โควตาวิศวกรรมศาสตร์ มอ.""",2000-01-26,60.0,ยะลา,TH,THAILAND,โรงเรียนธรรมวิทยามูลนิธิ,60,ยะลา,22.50,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,2.70,2.48,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,3.54,NaN,other,N,อยู่ด้วยกัน,9.0
4116,IY8jWx00mt,2564.0,1.0,226.0,วิศวกรรมการผลิต,31.0,ภาควิชาวิศวกรรมอุตสาหการ,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,239.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมการผลิต),หลักสูตรปกติ,OK,กำลังศึกษา,Y,T,ชาย,39,"โครงการ ""โควตาวิศวกรรมศาสตร์ มอ.""",2002-08-25,63.0,สตูล,TH,THAILAND,โรงเรียนควนโดนวิทยา,63,สตูล,37.50,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,3.27,3.27,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,3.74,NaN,other,N,อยู่ด้วยกัน,9.0
4117,uVfxDYkac8,2564.0,1.0,203.0,วิศวกรรมและการจัดการนวัตกรรม,193.0,คณะวิศวกรรมศาสตร์,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,4.0,ภาคปกติ (นานาชาติ),แผนการศึกษา ป.ตรี,254.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมและการจัดการนวัตก...,หลักสูตรนานาชาติ,OK,กำลังศึกษา,Y,T,หญิง,P4,โครงการคัดเลือกนักเรียนเข้าศึกษาในคณะวิศวกรรมศ...,2003-02-25,62.0,สงขลา,TH,THAILAND,โรงเรียนธิดานุเคราะห์,62,สงขลา,61.25,1.0,วิทยาเขตหาดใหญ่,N,FT,Y,Y,2.56,3.15,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,3.25,NaN,other,N,อยู่ด้วยกัน,9.0
4118,IcXALKhfPP,2564.0,1.0,203.0,วิศวกรรมและการจัดการนวัตกรรม,193.0,คณะวิศวกรรมศาสตร์,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,4.0,ภาคปกติ (นานาชาติ),แผนการศึกษา ป.ตรี,254.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมและการจัดการนวัตก...,หลักสูตรนานาชาติ,OK,กำลังศึกษา,Y,T,ชาย,P4,โครงการคัดเลือกนักเรียนเข้าศึกษาในคณะวิศวกรรมศ...,1998-04-01,63.0,สตูล,TH,THAILAND,โรงเรียนดารุลมาอาเรฟมูลนิธิ,63,สตูล,21.25,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,3.64,3.50,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,2.79,NaN,other,N,มารดาถึงแก่กรรม,8.0
4119,q5SWpcypnh,2564.0,1.0,203.0,วิศวกรรมและการจัดการนวัตกรรม,193.0,คณะวิศวกรรมศาสตร์,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,4.0,ภาคปกติ (นานาชาติ),แผนการศึกษา ป.ตรี,254.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมและการจัดการนวัตก...,หลักสูตรนานาชาติ,OK,กำลังศึกษา,Y,T,ชาย,P4,โครงการคัดเลือกนักเรียนเข้าศึกษาในคณะวิศวกรรมศ...,2003-01-30,54.0,นครศรีธรรมราช,TH,THAILAND,โรงเรียนปากพะยูนพิทยาคาร,58,พัทลุง,56.25,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,3.17,2.78,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,3.26,ไม่ได้รับทุน,N,N,อยู่ด้วยกัน,9.0

In [70]:
raw_datas[(raw_datas['FUND_NAME'] == 'ได้รับทุน')].count()

STUDENT_ID                   317
ADMIT_YEAR                   317
ADMIT_TERM                   317
MAJOR_ID                     317
MAJOR_NAME_THAI              317
DEPT_ID                      317
DEPT_NAME_THAI               317
FAC_ID                       317
FAC_NAME_THAI                317
STUDY_LEVEL_ID               317
STUDY_LEVEL_NAME             317
STUDY_TYPE_ID                317
STUDY_TYPE_NAME              317
STUDY_PLAN_NAME              303
DEGREE_ID                    303
COURSE_NAME                  317
COURSE_DEGREE                317
COURSE_TYPE_NAME             303
STUDY_STATUS                 317
STATUS_DESC_THAI             317
STILL_STUDENT                317
NATIONALITY                  317
SEX_NAME_THAI                317
ENT_METHOD                   317
ENT_METHOD_DESC              317
STUD_BIRTH_DATE              317
STUD_BIRTH_PROVINCE_ID       317
PROVINCE_NAME_THAI           317
BIRTH_COUNTRY                317
COUNTRY_NAME_ENG             317
PREV_INSTITUTION_NAME        317
INSTITUTION_PROVINCE_ID      317
INSTITUTION_PROVINCE_NAME    317
ENG_SCORE                    317
CAMPUS_ID                    317
CAMPUS_NAME_THAI             317
IS_GRAD_IN_COURSE            317
CURR_REG                     317
IN_PROVINCE                  317
IN_PROVINCE_CAMPUS           317
เกรดปี1เทอม1                 317
เกรดปี1เทอม2                 317
เกรดปี1เทอม3                 317
เกรดปี2เทอม1                 317
เกรดปี2เทอม2                 317
เกรดปี2เทอม3                 317
เกรดปี3เทอม1                 317
เกรดปี3เทอม2                 317
เกรดปี3เทอม3                 317
เกรดปี4เทอม1                 317
เกรดปี4เทอม2                 317
เกรดปี4เทอม3                 317
GPA_SCHOOL                   317
FUND_NAME                    317
FUND_NAME_CODE               317
DEFORMITY_NAME_code          317
PARENTS_MARRIED_NAME         317
PARENTS_MARRIED_NAME_CODE    317
dtype: int64

In [71]:
raw_datas[(raw_datas['FUND_NAME'] == 'ไม่ได้รับทุน') & (raw_datas['STUDY_STATUS'] == 'E') ].count()

STUDENT_ID                   211
ADMIT_YEAR                   211
ADMIT_TERM                   211
MAJOR_ID                     211
MAJOR_NAME_THAI              211
DEPT_ID                      211
DEPT_NAME_THAI               211
FAC_ID                       211
FAC_NAME_THAI                211
STUDY_LEVEL_ID               211
STUDY_LEVEL_NAME             211
STUDY_TYPE_ID                211
STUDY_TYPE_NAME              211
STUDY_PLAN_NAME              111
DEGREE_ID                    111
COURSE_NAME                  211
COURSE_DEGREE                211
COURSE_TYPE_NAME             111
STUDY_STATUS                 211
STATUS_DESC_THAI             211
STILL_STUDENT                211
NATIONALITY                  211
SEX_NAME_THAI                211
ENT_METHOD                   211
ENT_METHOD_DESC              211
STUD_BIRTH_DATE              211
STUD_BIRTH_PROVINCE_ID       211
PROVINCE_NAME_THAI           211
BIRTH_COUNTRY                211
COUNTRY_NAME_ENG             211
PREV_INSTITUTION_NAME        211
INSTITUTION_PROVINCE_ID      211
INSTITUTION_PROVINCE_NAME    211
ENG_SCORE                    211
CAMPUS_ID                    211
CAMPUS_NAME_THAI             211
IS_GRAD_IN_COURSE            211
CURR_REG                     211
IN_PROVINCE                  211
IN_PROVINCE_CAMPUS           211
เกรดปี1เทอม1                 211
เกรดปี1เทอม2                 211
เกรดปี1เทอม3                 211
เกรดปี2เทอม1                 211
เกรดปี2เทอม2                 211
เกรดปี2เทอม3                 211
เกรดปี3เทอม1                 211
เกรดปี3เทอม2                 211
เกรดปี3เทอม3                 211
เกรดปี4เทอม1                 211
เกรดปี4เทอม2                 211
เกรดปี4เทอม3                 211
GPA_SCHOOL                   211
FUND_NAME                    211
FUND_NAME_CODE               211
DEFORMITY_NAME_code          211
PARENTS_MARRIED_NAME         211
PARENTS_MARRIED_NAME_CODE    211
dtype: int64

In [72]:
raw_datas

,STUDENT_ID,ADMIT_YEAR,ADMIT_TERM,MAJOR_ID,MAJOR_NAME_THAI,DEPT_ID,DEPT_NAME_THAI,FAC_ID,FAC_NAME_THAI,STUDY_LEVEL_ID,STUDY_LEVEL_NAME,STUDY_TYPE_ID,STUDY_TYPE_NAME,STUDY_PLAN_NAME,DEGREE_ID,COURSE_NAME,COURSE_DEGREE,COURSE_TYPE_NAME,STUDY_STATUS,STATUS_DESC_THAI,STILL_STUDENT,NATIONALITY,SEX_NAME_THAI,ENT_METHOD,ENT_METHOD_DESC,STUD_BIRTH_DATE,STUD_BIRTH_PROVINCE_ID,PROVINCE_NAME_THAI,BIRTH_COUNTRY,COUNTRY_NAME_ENG,PREV_INSTITUTION_NAME,INSTITUTION_PROVINCE_ID,INSTITUTION_PROVINCE_NAME,ENG_SCORE,CAMPUS_ID,CAMPUS_NAME_THAI,IS_GRAD_IN_COURSE,CURR_REG,IN_PROVINCE,IN_PROVINCE_CAMPUS,เกรดปี1เทอม1,เกรดปี1เทอม2,เกรดปี1เทอม3,เกรดปี2เทอม1,เกรดปี2เทอม2,เกรดปี2เทอม3,เกรดปี3เทอม1,เกรดปี3เทอม2,เกรดปี3เทอม3,เกรดปี4เทอม1,เกรดปี4เทอม2,เกรดปี4เทอม3,GPA_SCHOOL,FUND_NAME,FUND_NAME_CODE,DEFORMITY_NAME_code,PARENTS_MARRIED_NAME,PARENTS_MARRIED_NAME_CODE
0,Y6rAL6a3ug,2559.0,1.0,215.0,วิศวกรรมเครื่องกล,30.0,ภาควิชาวิศวกรรมเครื่องกล,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,218.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมเครื่องกล),หลักสูตรปกติ,G,สำเร็จการศึกษา (พ้นสภาพการเป็นนักศึกษา),N,T,ชาย,77,โครงการคัดเลือกบุคคลเข้าศึกษาโดยใช้ผลคะแนนสอบ ...,1997-11-16,53.0,ตรัง,TH,THAILAND,โรงเรียนหาดใหญ่วิทยาลัยสมบูรณ์กุลกันยา,62,สงขลา,41.00,1.0,วิทยาเขตหาดใหญ่,Y,FT,N,Y,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,3.10,ไม่ได้รับทุน,N,N,อยู่ด้วยกัน,9.0
1,ihEYqG7Q2P,2559.0,1.0,225.0,วิศวกรรมอุตสาหการ,31.0,ภาควิชาวิศวกรรมอุตสาหการ,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,228.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมอุตสาหการ),หลักสูตรปกติ,E,ลาออก (พ้นสภาพการเป็นนักศึกษา),N,T,หญิง,01,โครงการคัดเลือกนักเรียนใน 14 จังหวัดภาคใต้ เข...,1998-01-12,61.0,ระนอง,TH,THAILAND,โรงเรียนศรียาภัย,52,ชุมพร,52.00,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,2.97,2.30,2.50,2.97,3.36,2.75,3.60,3.9,0.00,3.83,4.00,0.0,3.32,ไม่ได้รับทุน,N,N,อยู่ด้วยกัน,9.0
2,EJwFAHDeDB,2559.0,1.0,210.0,วิศวกรรมไฟฟ้า,28.0,ภาควิชาวิศวกรรมไฟฟ้า,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,213.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมไฟฟ้า),หลักสูตรปกติ,G,สำเร็จการศึกษา (พ้นสภาพการเป็นนักศึกษา),N,T,หญิง,40,"โครงการ ""ทุนมงคลสุข""",1997-02-24,62.0,สงขลา,TH,THAILAND,โรงเรียนจะนะชนูปถัมภ์,62,สงขลา,28.00,1.0,วิทยาเขตหาดใหญ่,Y,FT,Y,Y,1.73,1.05,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,3.78,ได้รับทุน,Y,N,บิดาและมารดาแต่งงานใหม่,4.0
3,mAN7tIZz44,2559.0,1.0,215.0,วิศวกรรมเครื่องกล,30.0,ภาควิชาวิศวกรรมเครื่องกล,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,218.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมเครื่องกล),หลักสูตรปกติ,R,ตกออก (พ้นสภาพการเป็นนักศึกษา),N,T,ชาย,01,โครงการคัดเลือกนักเรียนใน 14 จังหวัดภาคใต้ เข...,1997-09-01,60.0,ยะลา,TH,THAILAND,โรงเรียนราชมุนีรังสฤษฏ์,56,ปัตตานี,21.00,1.0,วิทยาเขตหาดใหญ่,Y,FT,N,N,2.50,2.94,3.25,3.47,3.27,3.23,3.47,0.0,3.31,3.73,0.00,0.0,3.77,ได้รับทุน,Y,N,บิดาถึงแก่กรรม,6.0
4,rWseDSww8R,2559.0,1.0,235.0,วิศวกรรมเหมืองแร่,33.0,ภาควิชาวิศวกรรมเหมืองแร่และวัสดุ,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,240.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมเหมืองแร่),หลักสูตรปกติ,G,สำเร็จการศึกษา (พ้นสภาพการเป็นนักศึกษา),N,T,ชาย,38,โครงการรับนักเรียนที่มีผลการเรียนดี,1997-10-05,63.0,สตูล,TH,THAILAND,โรงเรียนจุฬาภรณราชวิทยาลัย สตูล,63,สตูล,21.00,1.0,วิทยาเขตหาดใหญ่,Y,FT,N,N,1.93,2.08,1.86,1.78,0.00,2.08,1.41,0.0,0.87,1.22,0.72,0.0,3.21,ไม่ได้รับทุน,N,N,อยู่ด้วยกัน,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4115,mPcmlJsEow,2564.0,1.0,210.0,วิศวกรรมไฟฟ้า,28.0,ภาควิชาวิศวกรรมไฟฟ้า,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,213.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมไฟฟ้า),หลักสูตรปกติ,OK,กำลังศึกษา,Y,T,ชาย,39,"โครงการ ""โควตาวิศวกรรมศาสตร์ มอ.""",2000-01-26,60.0,ยะลา,TH,THAILAND,โรงเรียนธรรมวิทยามูลนิธิ,60,ยะลา,22.50,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,2.70,2.48,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,3.54,NaN,other,N,อยู่ด้วยกัน,9.0
4116,IY8jWx00mt,2564.0,1.0,226.0,วิศวกรรมการผลิต,31.0,ภาควิชาวิศวกรรมอุตสาหการ,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,1.0,ภาคปกติ,แผนการศึกษา ป.ตรี,239.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมการผลิต),หลักสูตรปกติ,OK,กำลังศึกษา,Y,T,ชาย,39,"โครงการ ""โควตาวิศวกรรมศาสตร์ มอ.""",2002-08-25,63.0,สตูล,TH,THAILAND,โรงเรียนควนโดนวิทยา,63,สตูล,37.50,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,3.27,3.27,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,3.74,NaN,other,N,อยู่ด้วยกัน,9.0
4117,uVfxDYkac8,2564.0,1.0,203.0,วิศวกรรมและการจัดการนวัตกรรม,193.0,คณะวิศวกรรมศาสตร์,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,4.0,ภาคปกติ (นานาชาติ),แผนการศึกษา ป.ตรี,254.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมและการจัดการนวัตก...,หลักสูตรนานาชาติ,OK,กำลังศึกษา,Y,T,หญิง,P4,โครงการคัดเลือกนักเรียนเข้าศึกษาในคณะวิศวกรรมศ...,2003-02-25,62.0,สงขลา,TH,THAILAND,โรงเรียนธิดานุเคราะห์,62,สงขลา,61.25,1.0,วิทยาเขตหาดใหญ่,N,FT,Y,Y,2.56,3.15,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,3.25,NaN,other,N,อยู่ด้วยกัน,9.0
4118,IcXALKhfPP,2564.0,1.0,203.0,วิศวกรรมและการจัดการนวัตกรรม,193.0,คณะวิศวกรรมศาสตร์,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,4.0,ภาคปกติ (นานาชาติ),แผนการศึกษา ป.ตรี,254.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมและการจัดการนวัตก...,หลักสูตรนานาชาติ,OK,กำลังศึกษา,Y,T,ชาย,P4,โครงการคัดเลือกนักเรียนเข้าศึกษาในคณะวิศวกรรมศ...,1998-04-01,63.0,สตูล,TH,THAILAND,โรงเรียนดารุลมาอาเรฟมูลนิธิ,63,สตูล,21.25,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,3.64,3.50,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,2.79,NaN,other,N,มารดาถึงแก่กรรม,8.0
4119,q5SWpcypnh,2564.0,1.0,203.0,วิศวกรรมและการจัดการนวัตกรรม,193.0,คณะวิศวกรรมศาสตร์,6.0,คณะวิศวกรรมศาสตร์,6.0,ปริญญาตรี,4.0,ภาคปกติ (นานาชาติ),แผนการศึกษา ป.ตรี,254.0,วิศวกรรมศาสตรบัณฑิต,วิศวกรรมศาสตรบัณฑิต (วิศวกรรมและการจัดการนวัตก...,หลักสูตรนานาชาติ,OK,กำลังศึกษา,Y,T,ชาย,P4,โครงการคัดเลือกนักเรียนเข้าศึกษาในคณะวิศวกรรมศ...,2003-01-30,54.0,นครศรีธรรมราช,TH,THAILAND,โรงเรียนปากพะยูนพิทยาคาร,58,พัทลุง,56.25,1.0,วิทยาเขตหาดใหญ่,N,FT,N,N,3.17,2.78,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,3.26,ไม่ได้รับทุน,N,N,อยู่ด้วยกัน,9.0

In [73]:
210/2517*100

8.34326579261025

In [74]:
18/292*100

6.164383561643835

In [75]:
import sklearn
from pycaret.classification import *
import numpy as np

In [76]:
clean_data = pd.read_csv('../data/data_dropout_59-64(clean_3).csv')

FileNotFoundError: [Errno 2] No such file or directory: '../data/data_dropout_59-64(clean_3).csv'

In [ ]:
pd.set_option('')

In [ ]:
clean_data.columns.to_list().index(('เกรดปี4เทอม2'))

19

In [ ]:
clean_data = clean_data.iloc[:,[1,5,12,13,14,15,16,17,18,19]]

In [ ]:
clean_data = clean_data.iloc[:,1:]

In [ ]:
clean_data = clean_data[(clean_data['STUDY_STATUS'] == 'R') | (clean_data['STUDY_STATUS'] == "G")]

In [ ]:
clean_data = clean_data[( (clean_data['STUDY_STATUS'] == 'G') & (clean_data['เกรดปี4เทอม1'] != 0) & (clean_data['เกรดปี3เทอม2'] != 0) ) | (clean_data['STUDY_STATUS'] == 'R') ]

In [ ]:
clean_data = clean_data.drop(['ENT_METHOD_DESC','STATUS_DESC_THAI','PROVINCE_NAME_THAI','PREV_INSTITUTION_NAME','INSTITUTION_PROVINCE_NAME','PARENTS_MARRIED_NAME','STILL_STUDENT','PARENTS_MARRIED_NAME_CODE'],axis=1)

In [ ]:
clean_data = clean_data.drop(['ENT_METHOD'],axis=1)

In [ ]:
clean_data

,STUDENT_ID,ADMIT_YEAR,MAJOR_ID,DEPT_ID,DEGREE_ID,STUDY_STATUS,STUD_BIRTH_PROVINCE_ID,INSTITUTION_PROVINCE_ID,ENG_SCORE,CAMPUS_ID,IS_GRAD_IN_COURSE,เกรดปี1เทอม1,เกรดปี1เทอม2,เกรดปี2เทอม1,เกรดปี2เทอม2,เกรดปี3เทอม1,เกรดปี3เทอม2,เกรดปี4เทอม1,เกรดปี4เทอม2,GPA_SCHOOL
0,mAN7tIZz44,2559,215,30,218.0,R,60,56,21.00,1,Y,2.50,2.94,3.47,3.27,3.47,0.00,3.73,0.00,3.77
1,cBjZzPJlAD,2559,215,30,218.0,G,64,64,20.00,1,Y,2.39,2.80,2.17,2.42,2.68,3.00,4.00,0.00,3.62
2,250t4hTHoh,2559,220,29,223.0,G,60,54,39.00,1,Y,2.00,2.88,2.75,3.00,3.13,2.93,3.50,0.00,3.05
3,rIV7hrbRCr,2559,215,30,218.0,G,62,62,37.00,1,Y,2.62,2.15,2.02,2.02,3.07,2.50,3.15,3.80,3.79
4,LcrgspJGLP,2559,230,32,233.0,G,54,54,34.00,1,Y,2.95,1.65,1.95,1.50,2.18,2.08,2.17,3.34,3.81
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
844,boLB4EhGgn,2564,254,33,149.0,R,62,62,30.00,1,N,2.97,3.28,0.00,0.00,0.00,0.00,0.00,0.00,3.17
845,qepZdMucLe,2564,200,193,200.0,R,62,62,28.75,1,N,2.90,3.54,0.00,0.00,0.00,0.00,0.00,0.00,3.13
846,vGwBUDfTQK,2564,254,33,149.0,R,62,62,23.75,1,N,3.76,2.75,0.00,0.00,0.00,0.00,0.00,0.00,3.61
847,7wYlFrxlfz,2564,225,31,228.0,R,63,63,28.75,1,N,3.52,3.78,0.00,0.00,0.00,0.00,0.00,0.00,3.72
848,nzfL04uMjS,2564,200,193,200.0,R,57,57,28.75,1,N,2.40,3.60,0.00,0.00,0.00,0.00,0.00,0.00,3.87

In [ ]:
for i in clean_data[clean_data['STUDY_STATUS'] == "G"]['PARENTS_MARRIED_NAME_CODE']:
    print(i)

9
4
9
9
9
9
9
10
9
9
1
6
6
9
9
6
10
2
10
9
9
9
9
9
10
9
9
9
9
9
2
9
9
2
10
2
9
9
9
9
9
10
9
9
9
9
9
9
9
9
9
9
10
9
9
9
9
9
9
2
10
9
9
9
9
10
9
6
9
9
10
9
9
10
9
9
9
9
9
2
9
5
9
9
3
9
9
9
9
9
9
9
10
9
9
9
9
9
9
2
10
9
9
4
9
9
9
9
1
9
9
9
9
9
9
9
9
3
9
9
9
10
2
10
10
10
1
9
2
1
9
9
9
9
9
9
6
9
9
10
10
9
9
9
9
9
9
3
10
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
2
10
9
9
9
9
9
9
9
9
9
2
2
6
9
9
9
9
2
9
9
10
9
9
9
9
9
9
9
9
9
9
6
9
10
10
9
9
9
9
9
9
9
10
9
10
9
9
9
9
9
9
9
9
10
10
9
9
9
9
9
9
9
9
2
9
9
10
2
9
11
6
9
8
9
10
9
6
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
6
1
9
9
9
9
9
9
9
9
10
9
9
9
9
6
6
9
9
9
9
9
9
6
9
1
9
9
9
9
2
5
9
9
9
9
9
9
9
10
8
9
10
9
9
9
9
9
9
9
9
9
9
9
9
9
9
10
9
6
9
5
2
9
9
9
9
9
6
9
9
9
9
10
9
9
2
9
9
9
9
9
9
9
9
9
10
9
9
9
9
9
9
10
9
9
2
10
9
9
9
10
9
9
9
9
6
9
6
9
9
9
9
9
9
9
9
9
9
9
9
9
2
9
9
6
10
9
9
9
9
9
10
9
9
10
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
8
9
10
9
10
6
9
10
9
9
9
9
5
6
9
9
9
6
9
6
9
9
9
9
9
9
9
1
9
8
9
9
9
9
9
9
1
2
8
9
9
9
9
9
9
10
9
6
9
9
2
9
9
9
2
9
9
9
9
9
9
9
9
9
9
10
9
9
9
9
9
9
10
9
10
9
9
9
9
9
9
9
9
2
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
2
3
9
9
9
11
9
9
9
9
9
6
9
9
9
9
9
9
9
10
10
6
9
9
9
9
10
9
9
9
9
9
9
9
9
9
9
10
9
9
9
9
10
9
9
10
9
9
9
9
9
9
9
9
9
9
9
9
6
9
9
9
9
10
1
9
2
9
9
9
9
2
1
10
9
9
9
9
9
9
10
9
9
9
2
9
4
9
9
4
9
9
8
9
9
9
10
9
9
9
2
9
9
9
10
9
6
9
6
9
6
9
9
9
2
10
9
9
9
9
1
9
9
9
6
10
9
9
9
9
9
9
9
6
9
9
3
9
9
9
10
9
9
9
9
9
9
9
9
4
9
9
2
9
9
10
9
9
9
2
6
9
9
9
9
9
9
9
9
9
10
10
9
2
9
9
9
1
9
2
9
9
2
9
9
10
9
9
10
9
9
10
9
9
9
9
9
9
9
9
9
9
6
9
9
9
10
9
2
6
9
9
9
10
9
6
1
6
1
9
10
10
9
9
9
9
9
9
9
1
9
9
9
9
9
9
2
9
6
9
9
9
9
9
9
9
10
9
9
10
1
9
9
9
9
9
9
9
9
8
9
9
8
1
9
9
2
9
9
9
9
9
9
9
9
10
9
9
9
6
9
9
6
9
9
6
10
1
9
10
9
9
9
9
9
6
9
9
8
2
9
9
9
9
9
9
9
9
9
9
9
1
9
9
9
2
9
9
9
9
9
9
9
9
9
8
6
9
9
9
2
9
9
9
9
10
1
9
9
9
9
9
7
9
9
9
9
9
10
9
1
9
9
9
9
9
9
6
9
9
9
9
9
9
9
9
6
9
9
9
9
9
9
10
9
9
9
9
1
9
9
9
9
9
9
9
9
9
9
10
5
9
9
9
9
9
9
9
9
9
9
9
9
9
10
9
9
9
9
9
9
9
9
2
9
9
9
9
2
9
9
9
9
9
9
10
9
9
10
9
9
9
9
9
9
9
9
2
9
9
10
9
9
9
9
9
9
9
9
9
10
9
10
9
9
9
9
9
9
2
10
10
9
9
9
6
9
2
9
6
9
9
6
6
9
9
9
9
9
9
2
9
9
9
2
9
9
10
9
9
9
9
9
9
9
9
9
9
9
9
9
6
9
9
9
9
9
9
10
9
9
9
9
6
9
10
10
9
10
10
4
9
9
9
9
9
9
9
9
9
1
9
9
9
10
9
9
6
2
9
4
10
9
9
9
9
9
1
2
9
9
9
9
10
9
9
9
9
9
9
9
9
9
1
9
9
9
9
9
6
9
9
9
7
9
9
9
9
6
9
10
9
9
9
9
9
9
9
9
9
9
2
9
4
9
9
6
10
9
9
9
6
9
9
9
10
10
2
9
9
2
10
9
9
9
6
9
7
9
9
6
9
9
9
9
9
9
9
9
6
9
9
9
9
9
9
6
10
9
9
10
9
9
9
9
9
9
9
9
9
9
8
9
9
9
9
9
9
9
10
9
9
9
10
9
9
9
9
9
9
9
9
9
9
2
9
9
9
9
9
6
9
9
9
6
2
9
9
9
9
9
9
9
9
9
9
9
9
3
10
9
9
10
9
9
9
9
10
9
9
9
9
10
9
9
9
9
9
9
9
9
10
9
6
10
9
9
9

In [ ]:
clean_data.to_csv('../data/data_dropout_59-64(clean_3).csv',index=False)

In [ ]:
sp = np.random.randint(0,848,size=(int(0.3*849)))

In [ ]:
ap = []

In [ ]:
a = np.arange(849)

In [ ]:
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
       195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
       208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
       221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
       234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
       247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259,
       260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272,
       273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
       286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298,
       299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
       312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324,
       325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337,
       338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350,
       351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363,
       364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376,
       377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389,
       390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402,
       403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415,
       416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428,
       429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441,
       442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454,
       455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467,
       468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480,
       481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493,
       494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506,
       507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519,
       520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532,
       533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545,
       546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558,
       559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571,
       572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584,
       585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597,
       598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610,
       611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623,
       624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636,
       637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649,
       650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662,
       663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675,
       676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688,
       689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701,
       702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714,
       715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727,
       728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740,
       741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753,
       754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766,
       767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779,
       780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792,
       793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805,
       806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818,
       819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831,
       832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844,
       845, 846, 847, 848])

In [ ]:
for i in a:
    if i not in sp:
        ap.append(i)

In [ ]:
2 in sp

True

In [ ]:
ap

[0,
 4,
 5,
 6,
 8,
 10,
 11,
 12,
 15,
 17,
 18,
 21,
 22,
 23,
 24,
 25,
 26,
 33,
 34,
 35,
 36,
 37,
 38,
 40,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 52,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 62,
 64,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 81,
 82,
 83,
 86,
 87,
 88,
 89,
 90,
 91,
 94,
 96,
 97,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 109,
 110,
 111,
 112,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 126,
 127,
 128,
 129,
 131,
 132,
 133,
 135,
 136,
 137,
 141,
 143,
 144,
 145,
 146,
 147,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 163,
 164,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 177,
 178,
 179,
 180,
 182,
 183,
 185,
 186,
 188,
 189,
 190,
 191,
 193,
 198,
 199,
 201,
 203,
 204,
 205,
 206,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 216,
 217,
 218,
 219,
 221,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 232,
 233,
 234,
 235,
 236,
 237,
 239,
 240,
 242,
 243,
 245,
 246,
 248,
 251,
 252,
 253,
 254,
 256,
 257,
 258,
 260,
 262,
 263,
 268,
 269,
 270,
 271,
 272,
 274,
 275,
 276,
 278,
 279,
 280,
 282,
 283,
 285,
 286,
 287,
 288,
 289,
 291,
 292,
 294,
 297,
 298,
 299,
 300,
 302,
 303,
 304,
 305,
 308,
 309,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 319,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 339,
 340,
 341,
 342,
 346,
 347,
 348,
 349,
 350,
 351,
 353,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 367,
 368,
 369,
 372,
 373,
 375,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 385,
 386,
 387,
 388,
 389,
 391,
 392,
 393,
 394,
 395,
 396,
 398,
 399,
 400,
 401,
 402,
 404,
 405,
 406,
 407,
 409,
 411,
 412,
 413,
 414,
 415,
 416,
 418,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 429,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 454,
 455,
 456,
 457,
 459,
 461,
 462,
 466,
 467,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 477,
 479,
 480,
 481,
 482,
 483,
 484,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 495,
 496,
 498,
 499,
 500,
 501,
 502,
 503,
 505,
 506,
 507,
 509,
 510,
 511,
 515,
 516,
 517,
 518,
 519,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 529,
 531,
 533,
 535,
 536,
 538,
 539,
 541,
 543,
 546,
 547,
 548,
 549,
 551,
 552,
 553,
 554,
 555,
 556,
 558,
 559,
 562,
 563,
 564,
 566,
 567,
 569,
 570,
 571,
 572,
 573,
 576,
 578,
 579,
 580,
 581,
 582,
 583,
 585,
 586,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 597,
 598,
 599,
 600,
 601,
 604,
 605,
 606,
 608,
 609,
 611,
 612,
 614,
 615,
 616,
 617,
 619,
 620,
 621,
 622,
 624,
 625,
 626,
 627,
 628,
 629,
 631,
 632,
 633,
 634,
 635,
 637,
 638,
 639,
 641,
 643,
 644,
 645,
 646,
 647,
 648,
 650,
 653,
 654,
 655,
 656,
 660,
 661,
 662,
 663,
 664,
 665,
 668,
 669,
 670,
 671,
 672,
 675,
 676,
 677,
 678,
 679,
 681,
 682,
 683,
 684,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 694,
 695,
 696,
 699,
 700,
 701,
 702,
 703,
 704,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 732,
 733,
 734,
 735,
 737,
 738,
 740,
 743,
 744,
 745,
 746,
 747,
 750,
 751,
 753,
 754,
 755,
 756,
 758,
 759,
 760,
 761,
 762,
 763,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 778,
 780,
 781,
 783,
 784,
 786,
 792,
 794,
 795,
 798,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 810,
 811,
 812,
 813,
 815,
 816,
 817,
 819,
 821,
 823,
 825,
 826,
 827,
 828,
 829,
 830,
 833,
 834,
 835,
 838,
 839,
 841,
 842,
 844,
 846,
 847,
 848]

In [ ]:
clean_data = clean_data.drop(['STILL_STUDENT'],axis=1)

In [ ]:
test = clean_data.iloc[sp]

In [ ]:
train = clean_data.iloc[ap]

In [ ]:
test = test.drop(['STATUS_DESC_THAI','PROVINCE_NAME_THAI','PREV_INSTITUTION_NAME','INSTITUTION_PROVINCE_NAME'],axis=1)

In [ ]:
train = train.drop(['STATUS_DESC_THAI','PROVINCE_NAME_THAI','PREV_INSTITUTION_NAME','INSTITUTION_PROVINCE_NAME'],axis=1)

In [ ]:
test

,STUDENT_ID,ADMIT_YEAR,MAJOR_ID,DEPT_ID,DEGREE_ID,STUDY_STATUS,ENT_METHOD,STUD_BIRTH_PROVINCE_ID,INSTITUTION_PROVINCE_ID,ENG_SCORE,...,IS_GRAD_IN_COURSE,เกรดปี1เทอม1,เกรดปี1เทอม2,เกรดปี2เทอม1,เกรดปี2เทอม2,เกรดปี3เทอม1,เกรดปี3เทอม2,เกรดปี4เทอม1,เกรดปี4เทอม2,GPA_SCHOOL
318,kV51YS6Evx,2559,240,34,243.0,G,03,11,11,0.00,...,Y,2.35,1.83,1.07,2.59,1.77,1.44,2.71,2.55,3.50
657,sO6HtS0myJ,2561,235,33,240.0,R,38,64,64,23.75,...,N,1.69,1.71,1.91,3.02,2.09,4.00,3.58,0.00,2.98
793,L7wgnYqnVB,2562,235,33,240.0,R,77,55,55,33.75,...,N,2.47,2.35,2.32,3.00,2.92,0.00,0.00,0.00,3.13
93,PXMjCP3lPG,2559,220,29,223.0,G,40,63,63,27.00,...,N,3.08,1.82,1.57,1.73,2.57,1.96,2.97,3.60,3.77
782,Y05zXI9F94,2561,240,34,243.0,G,33,55,55,0.00,...,Y,2.33,3.17,2.00,2.25,3.08,4.00,3.38,0.00,2.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113,1wZCyhEvh9,2559,225,31,228.0,G,01,54,54,26.00,...,Y,1.73,3.08,1.68,2.21,2.47,2.34,1.89,3.00,3.13
244,avMRKTHDw6,2559,240,34,243.0,R,36,62,62,21.00,...,N,1.50,2.02,2.25,2.08,2.75,2.77,2.85,2.86,2.86
410,fuD7aORlEA,2560,210,28,213.0,G,01,62,62,31.25,...,Y,3.10,2.52,2.52,2.63,3.10,3.00,4.00,0.00,2.93
417,zblZYkiigC,2560,220,29,223.0,G,10,60,60,40.00,...,Y,1.76,1.77,2.13,2.84,2.10,2.62,3.50,0.00,3.51
284,uPcn4P5dmO,2559,205,29,245.0,G,36,58,54,15.00,...,N,2.65,2.11,3.09,2.90,3.17,3.04,3.07,0.00,3.18

In [ ]:
clean_data.index

RangeIndex(start=0, stop=3510, step=1)

In [ ]:
s = setup(train,target='STUDY_STATUS')

In [ ]:
best_up_3 = compare_models()

NameError: name 'compare_models' is not defined

In [ ]:
best_up_1 = compare_models()

In [ ]:
best_2 = compare_models()

In [ ]:
best_1 = compare_models()

In [ ]:
best = compare_models()

In [ ]:
evaluate_model(best_1)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [ ]:
bestt = compare_models()

In [ ]:
besttt = compare_models()

In [ ]:
predictions = predict_model(best_3,data=test)

In [ ]:
predictions = predict_model(best_2,data=test)

In [ ]:
predictions = predict_model(best_3,data=test)

In [ ]:
best_3.feature_names_in_

array(['STUDENT_ID', 'ADMIT_YEAR', 'MAJOR_ID', 'DEPT_ID', 'DEGREE_ID',
       'ENT_METHOD', 'STUD_BIRTH_PROVINCE_ID', 'INSTITUTION_PROVINCE_ID',
       'ENG_SCORE', 'CAMPUS_ID', 'IS_GRAD_IN_COURSE', 'เกรดปี1เทอม1',
       'เกรดปี1เทอม2', 'เกรดปี2เทอม1', 'เกรดปี2เทอม2', 'เกรดปี3เทอม1',
       'เกรดปี3เทอม2', 'เกรดปี4เทอม1', 'เกรดปี4เทอม2', 'GPA_SCHOOL',
       'PARENTS_MARRIED_NAME_CODE'], dtype=object)

In [ ]:
predictions = predict_model(best_1,data=test)

In [ ]:
predictions = predict_model(bestt,data=test)

In [ ]:
predictions = predict_model(besttt,data=test)

In [ ]:
predictions = predict_model(load,data=test)

In [ ]:
predictions = predict_model(load,data=test)

In [ ]:
predictions = predict_model(best_up_3,data=test)

In [ ]:
predictions[(predictions['STUDY_STATUS'] == 'R') & (predictions['prediction_label'] == 'R')]

,STUDENT_ID,ADMIT_YEAR,MAJOR_ID,DEPT_ID,DEGREE_ID,STUD_BIRTH_PROVINCE_ID,INSTITUTION_PROVINCE_ID,ENG_SCORE,CAMPUS_ID,IS_GRAD_IN_COURSE,...,เกรดปี2เทอม1,เกรดปี2เทอม2,เกรดปี3เทอม1,เกรดปี3เทอม2,เกรดปี4เทอม1,เกรดปี4เทอม2,GPA_SCHOOL,STUDY_STATUS,prediction_label,prediction_score
7,AMOfPrIzEV,2559,200,193,0.0,52,62,34.00,1,N,...,1.72,1.97,2.83,2.65,2.72,3.42,3.50,R,R,0.9892
32,yjvqdTdHnF,2559,240,34,243.0,55,55,37.00,1,N,...,3.18,3.25,2.35,0.00,3.70,0.00,2.60,R,R,0.9876
33,wCIYO23RCJ,2559,226,31,239.0,60,62,34.00,1,N,...,1.27,1.92,0.47,0.25,0.00,0.00,2.61,R,R,0.9946
34,NRZs3o2fT1,2559,240,34,243.0,54,62,55.00,1,N,...,1.25,2.05,1.07,0.62,1.67,2.17,2.42,R,R,0.8240
43,nKqbggAU3i,2559,250,33,238.0,62,62,30.00,1,N,...,2.93,3.83,0.00,3.40,0.00,0.00,2.72,R,R,0.9876
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,G0dYQwpo3B,2564,240,34,243.0,53,53,33.75,1,N,...,0.00,0.00,0.00,0.00,0.00,0.00,3.74,R,R,0.9961
330,Iwc4uk5sNp,2564,254,33,149.0,56,56,47.50,1,N,...,0.00,0.00,0.00,0.00,0.00,0.00,2.69,R,R,0.9984
331,DhqdX6AykG,2564,240,34,243.0,64,64,41.25,1,N,...,0.00,0.00,0.00,0.00,0.00,0.00,3.29,R,R,0.9990
332,26yh5Qxvi7,2564,200,193,200.0,60,60,23.75,1,N,...,0.00,0.00,0.00,0.00,0.00,0.00,3.73,R,R,0.9972
333,qepZdMucLe,2564,200,193,200.0,62,62,28.75,1,N,...,0.00,0.00,0.00,0.00,0.00,0.00,3.13,R,R,0.9981

In [ ]:
best_up_3.feature_names_in_

array(['STUDENT_ID', 'ADMIT_YEAR', 'MAJOR_ID', 'DEPT_ID', 'DEGREE_ID',
       'STUD_BIRTH_PROVINCE_ID', 'INSTITUTION_PROVINCE_ID', 'ENG_SCORE',
       'CAMPUS_ID', 'IS_GRAD_IN_COURSE', 'เกรดปี1เทอม1', 'เกรดปี1เทอม2',
       'เกรดปี2เทอม1', 'เกรดปี2เทอม2', 'เกรดปี3เทอม1', 'เกรดปี3เทอม2',
       'เกรดปี4เทอม1', 'เกรดปี4เทอม2', 'GPA_SCHOOL'], dtype=object)

In [ ]:
save_model(best_up_3,'model_top_no_STILL_STUDENT_2Class')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=FastMemory(location=/tmp/joblib),
          steps=[('clean_column_names',
                  TransformerWrapper(exclude=None, include=None,
                                     transformer=CleanColumnNames(match='[\\]\\[\\,\\{\\}\\"\\:]+'))),
                 ('label_encoding',
                  TransformerWrapperWithInverse(exclude=None, include=None,
                                                transformer=LabelEncoder())),
                 ('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     includ...
                                             criterion='friedman_mse', init=None,
                                             learning_rate=0.1, loss='log_loss',
                                             max_depth=3, max_features=None,
                                             max_leaf_nodes=None,
                                             min_impurity_decrease=0.0,
                                             min_samples_leaf=1,
                                             min_samples_split=2,
                                             min_weight_fraction_leaf=0.0,
                                             n_estimators=100,
                                             n_iter_no_change=None,
                                             random_state=3381, subsample=1.0,
                                             tol=0.0001, validation_fraction=0.1,
                                             verbose=0, warm_start=False))],
          verbose=False),
 'model_top_no_STILL_STUDENT_2Class.pkl')

In [ ]:
load = load_model('model_top_no_STILL_STUDENT_2Class')

Transformation Pipeline and Model Successfully Loaded

In [ ]:
load

Pipeline(memory=FastMemory(location=/tmp/joblib),
         steps=[('clean_column_names',
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=CleanColumnNames(match='[\\]\\[\\,\\{\\}\\"\\:]+'))),
                ('label_encoding',
                 TransformerWrapperWithInverse(exclude=None, include=None,
                                               transformer=LabelEncoder())),
                ('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    includ...
                                            criterion='friedman_mse', init=None,
                                            learning_rate=0.1, loss='log_loss',
                                            max_depth=3, max_features=None,
                                            max_leaf_nodes=None,
                                            min_impurity_decrease=0.0,
                                            min_samples_leaf=1,
                                            min_samples_split=2,
                                            min_weight_fraction_leaf=0.0,
                                            n_estimators=100,
                                            n_iter_no_change=None,
                                            random_state=3381, subsample=1.0,
                                            tol=0.0001, validation_fraction=0.1,
                                            verbose=0, warm_start=False))],
         verbose=False)

In [ ]:
best_3.feature_names_in_

array(['STUDENT_ID', 'ADMIT_YEAR', 'MAJOR_ID', 'DEPT_ID', 'DEGREE_ID',
       'ENT_METHOD', 'STUD_BIRTH_PROVINCE_ID', 'INSTITUTION_PROVINCE_ID',
       'ENG_SCORE', 'CAMPUS_ID', 'IS_GRAD_IN_COURSE', 'เกรดปี1เทอม1',
       'เกรดปี1เทอม2', 'เกรดปี2เทอม1', 'เกรดปี2เทอม2', 'เกรดปี3เทอม1',
       'เกรดปี3เทอม2', 'เกรดปี4เทอม1', 'เกรดปี4เทอม2', 'GPA_SCHOOL'],
      dtype=object)

In [ ]:
test.columns

Index(['STUDENT_ID', 'ADMIT_YEAR', 'MAJOR_ID', 'DEPT_ID', 'DEGREE_ID',
       'STUDY_STATUS', 'ENT_METHOD', 'STUD_BIRTH_PROVINCE_ID',
       'INSTITUTION_PROVINCE_ID', 'ENG_SCORE', 'CAMPUS_ID',
       'IS_GRAD_IN_COURSE', 'เกรดปี1เทอม1', 'เกรดปี1เทอม2', 'เกรดปี2เทอม1',
       'เกรดปี2เทอม2', 'เกรดปี3เทอม1', 'เกรดปี3เทอม2', 'เกรดปี4เทอม1',
       'เกรดปี4เทอม2', 'GPA_SCHOOL'],
      dtype='object')

In [ ]:
load.feature_names_in_

['STUDENT_ID',
 'ADMIT_YEAR',
 'MAJOR_ID',
 'DEPT_ID',
 'DEGREE_ID',
 'STUD_BIRTH_PROVINCE_ID',
 'INSTITUTION_PROVINCE_ID',
 'ENG_SCORE',
 'CAMPUS_ID',
 'IS_GRAD_IN_COURSE',
 'เกรดปี1เทอม1',
 'เกรดปี1เทอม2',
 'เกรดปี2เทอม1',
 'เกรดปี2เทอม2',
 'เกรดปี3เทอม1',
 'เกรดปี3เทอม2',
 'เกรดปี4เทอม1',
 'เกรดปี4เทอม2',
 'GPA_SCHOOL',
 'STUDY_STATUS']

In [ ]:
load.feature_names_in_

['STUDENT_ID',
 'ADMIT_YEAR',
 'MAJOR_ID',
 'DEPT_ID',
 'DEGREE_ID',
 'STILL_STUDENT',
 'ENT_METHOD',
 'ENT_METHOD_DESC',
 'STUD_BIRTH_PROVINCE_ID',
 'INSTITUTION_PROVINCE_ID',
 'ENG_SCORE',
 'CAMPUS_ID',
 'IS_GRAD_IN_COURSE',
 'เกรดปี1เทอม1',
 'เกรดปี1เทอม2',
 'เกรดปี2เทอม1',
 'เกรดปี2เทอม2',
 'เกรดปี3เทอม1',
 'เกรดปี3เทอม2',
 'เกรดปี4เทอม1',
 'เกรดปี4เทอม2',
 'GPA_SCHOOL',
 'PARENTS_MARRIED_NAME',
 'PARENTS_MARRIED_NAME_CODE',
 'STUDY_STATUS']

In [ ]:
load.feature_names_in_

['STUDENT_ID',
 'ADMIT_YEAR',
 'MAJOR_ID',
 'DEPT_ID',
 'DEGREE_ID',
 'ENT_METHOD',
 'STUD_BIRTH_PROVINCE_ID',
 'INSTITUTION_PROVINCE_ID',
 'ENG_SCORE',
 'CAMPUS_ID',
 'IS_GRAD_IN_COURSE',
 'เกรดปี1เทอม1',
 'เกรดปี1เทอม2',
 'เกรดปี2เทอม1',
 'เกรดปี2เทอม2',
 'เกรดปี3เทอม1',
 'เกรดปี3เทอม2',
 'เกรดปี4เทอม1',
 'เกรดปี4เทอม2',
 'GPA_SCHOOL',
 'STUDY_STATUS']

In [ ]:
test

,STUDENT_ID,ADMIT_YEAR,MAJOR_ID,DEPT_ID,DEGREE_ID,STUDY_STATUS,STILL_STUDENT,ENT_METHOD,ENT_METHOD_DESC,STUD_BIRTH_PROVINCE_ID,INSTITUTION_PROVINCE_ID,ENG_SCORE,CAMPUS_ID,IS_GRAD_IN_COURSE,เกรดปี1เทอม1,เกรดปี1เทอม2,เกรดปี2เทอม1,เกรดปี2เทอม2,เกรดปี3เทอม1,เกรดปี3เทอม2,เกรดปี4เทอม1,เกรดปี4เทอม2,GPA_SCHOOL,PARENTS_MARRIED_NAME,PARENTS_MARRIED_NAME_CODE
2104,6rJjVNaZid,2562,226,31,239.0,OK,Y,36,Admission,51,51,38.75,1,N,3.18,1.69,1.31,2.20,2.36,3.02,0.00,0.0,3.26,แยกกันอยู่เพราะความจำเป็นเกี่ยวกับอาชีพ,1
393,H2iU5JErAg,2559,240,34,243.0,G,N,39,"โครงการ ""โควตาวิศวกรรมศาสตร์ มอ.""",64,64,36.00,1,N,3.02,2.72,2.54,4.00,2.40,0.00,4.00,0.0,3.42,อยู่ด้วยกัน,9
1843,FwGmYiwqFU,2562,214,28,211.0,OK,Y,10,โครงการความร่วมมือกับมูลนิธิส่งเสริมโอลิมปิกวิ...,55,55,51.25,1,N,2.86,2.84,2.21,4.00,3.44,0.00,0.00,0.0,3.72,อยู่ด้วยกัน,9
1515,z3wkNE1Bce,2561,205,29,245.0,E,N,39,"โครงการ ""โควตาวิศวกรรมศาสตร์ มอ.""",55,55,40.00,1,N,2.50,2.47,3.10,3.11,0.00,2.92,0.00,0.0,3.23,อยู่ด้วยกัน,9
3223,rdvYxJdjvu,2564,215,30,218.0,OK,Y,60,"โครงการ ""ลูกพระราชบิดา """,60,56,26.25,1,N,3.54,3.51,0.00,0.00,0.00,0.00,0.00,0.0,3.28,อยู่ด้วยกัน,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1369,hh4OQEYDJD,2560,240,34,243.0,G,N,01,สอบตรง(รับตรง 14 จังหวัดภาคใต้),59,59,0.00,3,N,2.65,1.72,2.06,1.96,1.52,2.45,1.57,1.3,2.34,อยู่ด้วยกัน,9
3330,azYPFYNBrO,2564,220,29,223.0,OK,Y,01,โครงการคัดเลือกนักเรียนใน 14 จังหวัดภาคใต้ เข...,63,63,45.00,1,N,3.15,3.60,0.00,0.00,0.00,0.00,0.00,0.0,3.91,บิดาถึงแก่กรรม,6
3433,iRiHsZdp5R,2564,214,28,211.0,OK,Y,36,Admission,53,53,36.25,1,N,0.45,0.00,0.00,0.00,0.00,0.00,0.00,0.0,3.83,อยู่ด้วยกัน,9
2958,uuyJgIqyyL,2564,216,30,242.0,OK,Y,38,โครงการรับนักเรียนที่มีผลการเรียนดี,40,62,31.25,1,N,3.06,3.64,0.00,0.00,0.00,0.00,0.00,0.0,3.33,แยกกันอยู่เพราะสาเหตุอื่น,2
161,eVwZGpJ2rK,2559,230,32,233.0,G,N,01,โครงการคัดเลือกนักเรียนใน 14 จังหวัดภาคใต้ เข...,62,56,62.00,1,Y,1.94,2.21,2.31,1.31,1.70,0.00,2.95,4.0,3.97,หย่าร้าง,10

In [ ]:
predictions = predict_model(load,data=test)

In [ ]:
predictions

,STUDENT_ID,ADMIT_YEAR,MAJOR_ID,DEPT_ID,DEGREE_ID,ENT_METHOD,STUD_BIRTH_PROVINCE_ID,INSTITUTION_PROVINCE_ID,ENG_SCORE,CAMPUS_ID,...,เกรดปี2เทอม1,เกรดปี2เทอม2,เกรดปี3เทอม1,เกรดปี3เทอม2,เกรดปี4เทอม1,เกรดปี4เทอม2,GPA_SCHOOL,STUDY_STATUS,prediction_label,prediction_score
0,NRZs3o2fT1,2559,240,34,243.0,01,54,62,55.00,1,...,1.25,2.05,1.07,0.62,1.67,2.17,2.42,R,R,0.9756
1,NRZs3o2fT1,2559,240,34,243.0,01,54,62,55.00,1,...,1.25,2.05,1.07,0.62,1.67,2.17,2.42,R,R,0.9756
2,NRZs3o2fT1,2559,240,34,243.0,01,54,62,55.00,1,...,1.25,2.05,1.07,0.62,1.67,2.17,2.42,R,R,0.9756
3,NRZs3o2fT1,2559,240,34,243.0,01,54,62,55.00,1,...,1.25,2.05,1.07,0.62,1.67,2.17,2.42,R,R,0.9756
4,g1cihSFGyX,2559,200,193,0.0,01,53,53,31.00,1,...,2.70,2.36,2.40,2.69,2.90,3.39,3.81,R,R,0.9842
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
757,9Yt3g43Dhx,2564,214,28,211.0,39,61,61,31.25,1,...,0.00,0.00,0.00,0.00,0.00,0.00,3.14,OK,OK,0.9954
758,y8rBIuSol4,2564,203,193,254.0,39,62,62,53.75,1,...,0.00,0.00,0.00,0.00,0.00,0.00,3.57,OK,OK,0.9906
759,aAI1ZYA6Ix,2564,254,33,149.0,39,62,62,25.00,1,...,0.00,0.00,0.00,0.00,0.00,0.00,3.52,OK,OK,0.9947
760,0wPAVAqsuv,2564,254,33,149.0,39,57,57,12.50,1,...,0.00,0.00,0.00,0.00,0.00,0.00,3.71,OK,OK,0.9652
761,uVfxDYkac8,2564,203,193,254.0,P4,62,62,61.25,1,...,0.00,0.00,0.00,0.00,0.00,0.00,3.25,OK,OK,0.9911