In [1]:
import pandas 

df = pandas.read_excel("data/data_dropout_59-64.xlsx")

# remove last Row have NaN
df = df.drop(labels=[4120],axis=0)
df = df.drop(columns=['STUDENT_ID', 'MAJOR_NAME_THAI', 'DEPT_NAME_THAI', 'FAC_ID', 'FAC_NAME_THAI',
       'STUDY_LEVEL_ID', 'STUDY_LEVEL_NAME', 'STUDY_TYPE_ID',
       'STUDY_TYPE_NAME', 'STUDY_PLAN_NAME', 'DEGREE_ID', 'COURSE_NAME',
       'COURSE_DEGREE', 'COURSE_TYPE_NAME', 'STATUS_DESC_THAI',
       'STILL_STUDENT', 'NATIONALITY', 'SEX_SHORT_NAME_THAI', 'SEX_NAME_THAI',
       'ENT_METHOD', 'ENT_METHOD_DESC', 'STUD_BIRTH_DATE',
       'STUD_BIRTH_PROVINCE_ID', 'PROVINCE_NAME_THAI', 'BIRTH_COUNTRY',
       'COUNTRY_NAME_ENG', 'PREV_INSTITUTION_NAME', 'INSTITUTION_PROVINCE_ID',
       'INSTITUTION_PROVINCE_NAME', 'ENG_SCORE', 'CAMPUS_ID',
       'CAMPUS_NAME_THAI', 'IS_GRAD_IN_COURSE', 'CURR_REG', 'IN_PROVINCE',
       'IN_PROVINCE_CAMPUS', 'เกรดปี1เทอม3',
       'เกรดปี2เทอม1', 'เกรดปี2เทอม2', 'เกรดปี2เทอม3', 'เกรดปี3เทอม1',
       'เกรดปี3เทอม2', 'เกรดปี3เทอม3', 'เกรดปี4เทอม1', 'เกรดปี4เทอม2',
       'เกรดปี4เทอม3', 'FUND_NAME', 'FUND_NAME_CODE',
       'DEFORMITY_NAME', 'DEFORMITY_NAME_code', 'PARENTS_MARRIED_NAME',
       'PARENTS_MARRIED_NAME_CODE'], axis=1)
df

,ADMIT_YEAR,ADMIT_TERM,MAJOR_ID,DEPT_ID,STUDY_STATUS,เกรดปี1เทอม1,เกรดปี1เทอม2,GPA_SCHOOL
0,2559.0,1.0,215.0,30.0,G,NaN,NaN,3.10
1,2559.0,1.0,225.0,31.0,E,2.97,2.30,3.32
2,2559.0,1.0,210.0,28.0,G,1.73,1.05,3.78
3,2559.0,1.0,215.0,30.0,R,2.50,2.94,3.77
4,2559.0,1.0,235.0,33.0,G,1.93,2.08,3.21
...,...,...,...,...,...,...,...,...
4115,2564.0,1.0,210.0,28.0,OK,2.70,2.48,3.54
4116,2564.0,1.0,226.0,31.0,OK,3.27,3.27,3.74
4117,2564.0,1.0,203.0,193.0,OK,2.56,3.15,3.25
4118,2564.0,1.0,203.0,193.0,OK,3.64,3.50,2.79
4119,2564.0,1.0,203.0,193.0,OK,3.17,2.78,3.26

In [2]:
df.columns

Index(['ADMIT_YEAR', 'ADMIT_TERM', 'MAJOR_ID', 'DEPT_ID', 'STUDY_STATUS',
       'เกรดปี1เทอม1', 'เกรดปี1เทอม2', 'GPA_SCHOOL'],
      dtype='object')

In [3]:
df = df.drop(df[df['เกรดปี1เทอม1'].isna() | df['เกรดปี1เทอม2'].isna() | df['GPA_SCHOOL'].isna()].index)
df = df.drop(df[df['GPA_SCHOOL'] > 4].index)
df['GPA_SCHOOL'].unique()

array([3.32, 3.78, 3.77, 3.21, 3.62, 3.05, 3.79, 3.07, 3.71, 3.81, 3.72,
       3.98, 3.52, 3.54, 3.49, 2.6 , 3.5 , 3.67, 3.6 , 3.59, 3.56, 3.36,
       3.41, 3.16, 2.82, 3.58, 3.82, 3.25, 3.63, 3.55, 3.46, 3.35, 3.94,
       3.09, 2.65, 3.74, 3.53, 3.4 , 3.96, 3.85, 3.43, 3.37, 3.68, 3.64,
       2.23, 3.38, 3.76, 3.87, 3.14, 3.88, 3.8 , 3.3 , 3.69, 3.95, 2.51,
       3.42, 3.19, 3.15, 3.45, 3.73, 3.31, 3.48, 2.69, 2.99, 3.86, 3.08,
       3.7 , 2.61, 2.42, 3.22, 2.91, 3.39, 3.75, 3.34, 2.1 , 3.18, 2.88,
       3.92, 3.1 , 2.83, 3.29, 2.54, 3.89, 2.98, 2.85, 3.61, 3.97, 2.8 ,
       3.13, 3.51, 3.66, 3.33, 2.72, 3.9 , 2.89, 2.73, 3.65, 2.68, 3.47,
       3.26, 3.84, 3.28, 2.78, 3.57, 3.23, 3.2 , 3.03, 3.44, 2.81, 2.97,
       3.17, 3.12, 2.86, 2.92, 3.06, 2.7 , 3.83, 2.25, 3.01, 2.96, 3.99,
       2.55, 2.64, 2.84, 3.27, 3.  , 3.04, 3.02, 3.24, 2.93, 2.79, 2.77,
       2.59, 2.71, 1.93, 2.76, 2.52, 1.94, 2.47, 2.63, 2.57, 2.62, 2.35,
       2.38, 2.33, 2.53, 2.56, 2.95, 2.9 , 2.37, 2.26, 2.75, 2.17, 2.74,
       2.07, 2.34, 2.43, 2.5 , 2.4 , 3.11, 2.44, 2.49, 2.58, 2.94, 2.87,
       2.31, 2.67, 2.48, 1.97, 2.46, 3.93, 2.66, 2.41, 2.3 , 1.86, 2.45,
       2.16, 1.98, 2.21, 1.85, 2.32, 2.39, 2.2 , 1.79, 2.22, 2.13, 2.36,
       2.28, 2.06, 2.09, 2.08, 3.91, 1.88, 0.  , 2.19, 4.  , 1.95])

In [4]:
data_test = df.groupby("ADMIT_YEAR").sample(n=1, random_state=20)
df = df.drop(data_test.index)

data_test

,ADMIT_YEAR,ADMIT_TERM,MAJOR_ID,DEPT_ID,STUDY_STATUS,เกรดปี1เทอม1,เกรดปี1เทอม2,GPA_SCHOOL
673,2559.0,1.0,240.0,34.0,R,2.50,1.40,3.34
918,2560.0,1.0,226.0,31.0,G,3.61,3.02,2.50
1892,2561.0,1.0,226.0,31.0,OK,2.93,2.50,3.28
2290,2562.0,1.0,200.0,193.0,E,2.00,2.02,3.34
3021,2563.0,1.0,220.0,29.0,OK,3.10,2.54,2.93
3563,2564.0,1.0,214.0,28.0,OK,3.68,3.77,3.69

In [5]:
from pycaret.classification import *

In [6]:
# STUDY_STATUS
experiment = setup(df, target="STUDY_STATUS" )

In [7]:
best_model = compare_models()
best_model

Initiated  . . . . . . . . . . . . . . . . . .             10:24:36
Status     . . . . . . . . . . . . . . . . . .     Fitting 10 Folds
Estimator  . . . . . . . . . . . . . . . . . .  Logistic Regression

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=3548, verbose=0, warm_start=False)

In [ ]:
predictions = predict_model(best_model, data=data_test)

In [ ]:
predictions